export const DEFAULT_COUNTRY_CODE = "CR";

const RAW_COUNTRY_OPTIONS = [
  { code: "AD", name: "Andorra" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "AF", name: "Afghanistan" },
  { code: "AG", name: "Antigua & Barbuda" },
  { code: "AI", name: "Anguilla" },
  { code: "AL", name: "Albania" },
  { code: "AM", name: "Armenia" },
  { code: "AO", name: "Angola" },
  { code: "AQ", name: "Antarctica" },
  { code: "AR", name: "Argentina" },
  { code: "AS", name: "Samoa (American)" },
  { code: "AT", name: "Austria" },
  { code: "AU", name: "Australia" },
  { code: "AW", name: "Aruba" },
  { code: "AX", name: "Åland Islands" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BA", name: "Bosnia & Herzegovina" },
  { code: "BB", name: "Barbados" },
  { code: "BD", name: "Bangladesh" },
  { code: "BE", name: "Belgium" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BG", name: "Bulgaria" },
  { code: "BH", name: "Bahrain" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BN", name: "Brunei" },
  { code: "BO", name: "Bolivia" },
  { code: "BQ", name: "Caribbean NL" },
  { code: "BR", name: "Brazil" },
  { code: "BS", name: "Bahamas" },
  { code: "BT", name: "Bhutan" },
  { code: "BW", name: "Botswana" },
  { code: "BY", name: "Belarus" },
  { code: "BZ", name: "Belize" },
  { code: "CA", name: "Canada" },
  { code: "CD", name: "Congo (Dem. Rep.)" },
  { code: "CG", name: "Congo (Rep.)" },
  { code: "CH", name: "Switzerland" },
  { code: "CI", name: "Côte d’Ivoire" },
  { code: "CL", name: "Chile" },
  { code: "CM", name: "Cameroon" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "CV", name: "Cape Verde" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DE", name: "Germany" },
  { code: "DJ", name: "Djibouti" },
  { code: "DK", name: "Denmark" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "DZ", name: "Algeria" },
  { code: "EC", name: "Ecuador" },
  { code: "EE", name: "Estonia" },
  { code: "EG", name: "Egypt" },
  { code: "ES", name: "Spain" },
  { code: "ET", name: "Ethiopia" },
  { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fiji" },
  { code: "FM", name: "Micronesia" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GB", name: "Britain (UK)" },
  { code: "GD", name: "Grenada" },
  { code: "GE", name: "Georgia" },
  { code: "GF", name: "French Guiana" },
  { code: "GG", name: "Guernsey" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GL", name: "Greenland" },
  { code: "GN", name: "Guinea" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GR", name: "Greece" },
  { code: "GT", name: "Guatemala" },
  { code: "GU", name: "Guam" },
  { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hong Kong" },
  { code: "HN", name: "Honduras" },
  { code: "HR", name: "Croatia" },
  { code: "HT", name: "Haiti" },
  { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IM", name: "Isle of Man" },
  { code: "IN", name: "India" },
  { code: "IQ", name: "Iraq" },
  { code: "IR", name: "Iran" },
  { code: "IS", name: "Iceland" },
  { code: "IT", name: "Italy" },
  { code: "JE", name: "Jersey" },
  { code: "JM", name: "Jamaica" },
  { code: "JO", name: "Jordan" },
  { code: "JP", name: "Japan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "KH", name: "Cambodia" },
  { code: "KN", name: "St Kitts & Nevis" },
  { code: "KR", name: "Korea (South)" },
  { code: "KW", name: "Kuwait" },
  { code: "KY", name: "Cayman Islands" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Lebanon" },
  { code: "LC", name: "St Lucia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "LV", name: "Latvia" },
  { code: "LY", name: "Libya" },
  { code: "MA", name: "Morocco" },
  { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldova" },
  { code: "ME", name: "Montenegro" },
  { code: "MF", name: "St Martin (French)" },
  { code: "MG", name: "Madagascar" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MK", name: "North Macedonia" },
  { code: "ML", name: "Mali" },
  { code: "MM", name: "Myanmar (Burma)" },
  { code: "MN", name: "Mongolia" },
  { code: "MO", name: "Macau" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MT", name: "Malta" },
  { code: "MU", name: "Mauritius" },
  { code: "MV", name: "Maldives" },
  { code: "MW", name: "Malawi" },
  { code: "MX", name: "Mexico" },
  { code: "MY", name: "Malaysia" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibia" },
  { code: "NC", name: "New Caledonia" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" },
  { code: "NL", name: "Netherlands" },
  { code: "NO", name: "Norway" },
  { code: "NP", name: "Nepal" },
  { code: "NZ", name: "New Zealand" },
  { code: "OM", name: "Oman" },
  { code: "PA", name: "Panama" },
  { code: "PE", name: "Peru" },
  { code: "PF", name: "French Polynesia" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PH", name: "Philippines" },
  { code: "PK", name: "Pakistan" },
  { code: "PL", name: "Poland" },
  { code: "PM", name: "St Pierre & Miquelon" },
  { code: "PR", name: "Puerto Rico" },
  { code: "PS", name: "Palestine" },
  { code: "PT", name: "Portugal" },
  { code: "PW", name: "Palau" },
  { code: "PY", name: "Paraguay" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RS", name: "Serbia" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SC", name: "Seychelles" },
  { code: "SD", name: "Sudan" },
  { code: "SE", name: "Sweden" },
  { code: "SG", name: "Singapore" },
  { code: "SI", name: "Slovenia" },
  { code: "SK", name: "Slovakia" },
  { code: "SM", name: "San Marino" },
  { code: "SN", name: "Senegal" },
  { code: "SO", name: "Somalia" },
  { code: "SR", name: "Suriname" },
  { code: "ST", name: "Sao Tome & Principe" },
  { code: "SV", name: "El Salvador" },
  { code: "SX", name: "St Maarten (Dutch)" },
  { code: "SY", name: "Syria" },
  { code: "SZ", name: "Eswatini (Swaziland)" },
  { code: "TC", name: "Turks & Caicos Is" },
  { code: "TG", name: "Togo" },
  { code: "TH", name: "Thailand" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TL", name: "East Timor" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TT", name: "Trinidad & Tobago" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" },
  { code: "UA", name: "Ukraine" },
  { code: "UG", name: "Uganda" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VC", name: "St Vincent" },
  { code: "VE", name: "Venezuela" },
  { code: "VG", name: "Virgin Islands (UK)" },
  { code: "VI", name: "Virgin Islands (US)" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "YT", name: "Mayotte" },
  { code: "ZA", name: "South Africa" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
] as const;

export const COUNTRY_OPTIONS = [...RAW_COUNTRY_OPTIONS].sort((a, b) => {
  if (a.code === DEFAULT_COUNTRY_CODE) return -1;
  if (b.code === DEFAULT_COUNTRY_CODE) return 1;
  return a.name.localeCompare(b.name);
});

const COUNTRY_NAME_BY_CODE = new Map<string, string>(
  RAW_COUNTRY_OPTIONS.map(({ code, name }) => [code, name]),
);

export function normalizeCountryCode(code?: string | null): string {
  const normalized = code?.trim().toUpperCase();
  if (!normalized || !COUNTRY_NAME_BY_CODE.has(normalized)) {
    return DEFAULT_COUNTRY_CODE;
  }
  return normalized;
}

export function isSupportedCountryCode(code?: string | null): boolean {
  const normalized = code?.trim().toUpperCase();
  return !!normalized && COUNTRY_NAME_BY_CODE.has(normalized);
}

export function getCountryName(code?: string | null): string {
  const normalized = normalizeCountryCode(code);
  return COUNTRY_NAME_BY_CODE.get(normalized) ?? normalized;
}

export function getCountryFlagEmoji(code?: string | null): string {
  const normalized = normalizeCountryCode(code);
  return String.fromCodePoint(
    ...normalized
      .split("")
      .map((char) => 127397 + char.charCodeAt(0)),
  );
}

export function getCountryFlagUrl(code?: string | null): string {
  const normalized = normalizeCountryCode(code);
  return `https://osu.ppy.sh/images/flags/${normalized}.png`;
}

/**
 * Returns a CSS gradient approximating the country's flag for use on the osu! logo circle.
 * Only covers countries with simple stripe-based flags. Returns null for complex flags,
 * in which case the caller should fall back to the flag image.
 */
const FLAG_GRADIENTS: Record<string, string> = {
  // Horizontal stripes (top to bottom)
  CR: "linear-gradient(180deg, #002b7f 20%, #fff 20%, #fff 35%, #ce1126 35%, #ce1126 65%, #fff 65%, #fff 80%, #002b7f 80%)",
  DE: "linear-gradient(180deg, #000 33%, #dd0000 33%, #dd0000 67%, #ffcc00 67%)",
  FR: "linear-gradient(90deg, #002395 33%, #fff 33%, #fff 67%, #ed2939 67%)",
  IT: "linear-gradient(90deg, #009246 33%, #fff 33%, #fff 67%, #ce2b37 67%)",
  NL: "linear-gradient(180deg, #ae1c28 33%, #fff 33%, #fff 67%, #21468b 67%)",
  RU: "linear-gradient(180deg, #fff 33%, #0039a6 33%, #0039a6 67%, #d52b1e 67%)",
  UA: "linear-gradient(180deg, #005bbb 50%, #ffd500 50%)",
  PL: "linear-gradient(180deg, #fff 50%, #dc143c 50%)",
  AT: "linear-gradient(180deg, #ed2939 33%, #fff 33%, #fff 67%, #ed2939 67%)",
  HU: "linear-gradient(180deg, #ce2939 33%, #fff 33%, #fff 67%, #477050 67%)",
  BG: "linear-gradient(180deg, #fff 33%, #00966e 33%, #00966e 67%, #d62612 67%)",
  LU: "linear-gradient(180deg, #ed2939 33%, #fff 33%, #fff 67%, #00a1de 67%)",
  BE: "linear-gradient(90deg, #000 33%, #ffd90c 33%, #ffd90c 67%, #f31830 67%)",
  IE: "linear-gradient(90deg, #169b62 33%, #fff 33%, #fff 67%, #ff883e 67%)",
  RO: "linear-gradient(90deg, #002b7f 33%, #fcd116 33%, #fcd116 67%, #ce1126 67%)",
  CO: "linear-gradient(180deg, #fcd116 50%, #003893 75%, #ce1126 75%)",
  AR: "linear-gradient(180deg, #74acdf 33%, #fff 33%, #fff 67%, #74acdf 67%)",
  CL: "linear-gradient(#0039a6, #0039a6) top left / 50% 50% no-repeat, linear-gradient(180deg, #fff 50%, #d52b1e 50%)",
  PE: "linear-gradient(90deg, #d91023 33%, #fff 33%, #fff 67%, #d91023 67%)",
  JP: "radial-gradient(circle, #bc002d 30%, #fff 30%)",
  KR: "linear-gradient(180deg, #fff 30%, #cd2e3a 50%, #0047a0 70%, #fff 70%)",
  TH: "linear-gradient(180deg, #ed1c24 17%, #fff 17%, #fff 33%, #241d4f 33%, #241d4f 67%, #fff 67%, #fff 83%, #ed1c24 83%)",
  ID: "linear-gradient(180deg, #ce1126 50%, #fff 50%)",
  PH: "linear-gradient(180deg, #0038a8 50%, #ce1126 50%)",
  US: "linear-gradient(#3c3b6e, #3c3b6e) top left / 40% 54% no-repeat, linear-gradient(180deg, #b22234 8%, #fff 8%, #fff 15%, #b22234 15%, #b22234 23%, #fff 23%, #fff 31%, #b22234 31%, #b22234 38%, #fff 38%, #fff 46%, #b22234 46%, #b22234 54%, #fff 54%, #fff 62%, #b22234 62%, #b22234 69%, #fff 69%, #fff 77%, #b22234 77%, #b22234 85%, #fff 85%, #fff 92%, #b22234 92%)",
  CA: "linear-gradient(90deg, #ff0000 25%, #fff 25%, #fff 75%, #ff0000 75%)",
  MX: "linear-gradient(90deg, #006847 33%, #fff 33%, #fff 67%, #ce1126 67%)",
  SE: "linear-gradient(180deg, #005293 40%, #fecc02 40%, #fecc02 60%, #005293 60%)",
  NO: "linear-gradient(180deg, #ef2b2d 30%, #fff 30%, #fff 38%, #002868 38%, #002868 62%, #fff 62%, #fff 70%, #ef2b2d 70%)",
  DK: "linear-gradient(180deg, #c8102e 43%, #fff 43%, #fff 57%, #c8102e 57%)",
  FI: "linear-gradient(180deg, #fff 40%, #003580 40%, #003580 60%, #fff 60%)",
  ES: "linear-gradient(180deg, #aa151b 25%, #f1bf00 25%, #f1bf00 75%, #aa151b 75%)",
  PT: "linear-gradient(90deg, #006600 40%, #ff0000 40%)",
  GR: "linear-gradient(180deg, #0d5eaf 11%, #fff 11%, #fff 22%, #0d5eaf 22%, #0d5eaf 33%, #fff 33%, #fff 44%, #0d5eaf 44%, #0d5eaf 56%, #fff 56%, #fff 67%, #0d5eaf 67%, #0d5eaf 78%, #fff 78%, #fff 89%, #0d5eaf 89%)",
  IN: "linear-gradient(180deg, #ff9933 33%, #fff 33%, #fff 67%, #138808 67%)",
  EG: "linear-gradient(180deg, #ce1126 33%, #fff 33%, #fff 67%, #000 67%)",
  NG: "linear-gradient(90deg, #008751 33%, #fff 33%, #fff 67%, #008751 67%)",
  ZA: "linear-gradient(180deg, #e03c31 33%, #fff 33%, #fff 37%, #007749 37%, #007749 63%, #fff 63%, #fff 67%, #001489 67%)",
  SG: "linear-gradient(180deg, #ee2536 50%, #fff 50%)",
  CZ: "linear-gradient(180deg, #fff 50%, #d7141a 50%)",
  EC: "linear-gradient(180deg, #ffd100 50%, #034ea2 75%, #ce1126 75%)",
  VE: "linear-gradient(180deg, #fcf75e 33%, #0035ad 33%, #0035ad 67%, #cf142b 67%)",
  PY: "linear-gradient(180deg, #d52b1e 33%, #fff 33%, #fff 67%, #0038a8 67%)",
  BO: "linear-gradient(180deg, #d52b1e 33%, #f9e300 33%, #f9e300 67%, #007934 67%)",
  GT: "linear-gradient(90deg, #4997d0 33%, #fff 33%, #fff 67%, #4997d0 67%)",
  HN: "linear-gradient(180deg, #0073cf 33%, #fff 33%, #fff 67%, #0073cf 67%)",
  SV: "linear-gradient(180deg, #0047ab 33%, #fff 33%, #fff 67%, #0047ab 67%)",
  NI: "linear-gradient(180deg, #0067c6 33%, #fff 33%, #fff 67%, #0067c6 67%)",
  BZ: "linear-gradient(180deg, #ce1126 10%, #003f87 10%, #003f87 90%, #ce1126 90%)",
  DO: "linear-gradient(180deg, #002d62 33%, #fff 33%, #fff 67%, #ce1126 67%)",
};

export function getCountryFlagGradient(code?: string | null): string | null {
  const normalized = normalizeCountryCode(code);
  return FLAG_GRADIENTS[normalized] ?? null;
}
