// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { I18nProvider } from "@lingui/react";
import { getI18n } from "#/lib/i18n";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import type { CollectedCard } from "#/lib/pack-collection";
import type { ReactNode } from "react";
const { search, send, inbox, dismiss } = vi.hoisted(() => ({ search: vi.fn(), send: vi.fn(), inbox: vi.fn(), dismiss: vi.fn() }));
vi.mock("#/lib/pack-gifts", () => ({ searchOwnGiftRecipients: search, sendOwnPackGift: send, fetchOwnPackGifts: inbox, dismissOwnPackGifts: dismiss }));
vi.mock("./PackDialog", () => ({ PackDialog: ({ title, children }: { title: string; children: ReactNode }) => <div role="dialog" aria-label={title}>{children}</div> }));
vi.mock("./CardTile", () => ({ CollectionCardTile: ({ card }: { card: { username: string } }) => <div>{card.username} card</div> }));
vi.mock("./useCardThumbnails", () => ({ useCardThumbnails: () => ({ onThumbnailError: () => {} }) }));
vi.mock("./cardThumbnailCache", () => ({ cardThumbnailKeyForCollectionCard: () => "key", getMemoryCardThumbnail: () => null }));
import { GiftSpareDialog } from "./GiftSpareDialog";
import { GiftInbox } from "./GiftInbox";
const card: CollectedCard = { userId: 77, cardKey: "77", username: "Friend", avatarUrl: "https://a.ppy.sh/77", countryCode: "CR", tier: "rare", tierLabel: "Rare", skills: null, pp: 1000, globalRank: 20, copies: 3, recycledCopies: 0, firstPulledAt: 1, lastPulledAt: 1 };
const recipient = { userId: 102, username: "Recipient", avatarUrl: "https://a.ppy.sh/102", countryCode: "CR" };
const wrap = (children: ReactNode) => <I18nProvider i18n={getI18n("en")}>{children}</I18nProvider>;
beforeEach(() => { vi.clearAllMocks(); search.mockResolvedValue([recipient]); send.mockResolvedValue({ ok: true, giftId: 1, recipient, remainingCopies: 2, replayed: false }); });
afterEach(cleanup);
it("selects and confirms the recipient before sending exactly one named card", async () => {
  const onSent = vi.fn();
  render(wrap(<GiftSpareDialog card={card} onClose={() => {}} onSent={onSent} />));
  expect(send).not.toHaveBeenCalled();
  fireEvent.change(screen.getByRole("textbox", { name: "Find a collector" }), { target: { value: "Reci" } });
  fireEvent.click(await screen.findByRole("button", { name: "Recipient" }));
  expect(send).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Send to Recipient" }));
  await screen.findByRole("status");
  expect(send).toHaveBeenCalledWith({ data: { recipientUserId: 102, cardKey: "77", requestId: expect.any(String) } });
  expect(onSent).toHaveBeenCalledTimes(1);
});
it("reuses the same request id when delivery could not be confirmed", async () => {
  send.mockRejectedValueOnce(new Error("connection lost"));
  const onSent = vi.fn();
  render(wrap(<GiftSpareDialog card={card} onClose={() => {}} onSent={onSent} />));
  fireEvent.change(screen.getByRole("textbox"), { target: { value: "Reci" } });
  fireEvent.click(await screen.findByRole("button", { name: "Recipient" }));
  fireEvent.click(screen.getByRole("button", { name: "Send to Recipient" }));
  await screen.findByRole("alert");
  expect(onSent).not.toHaveBeenCalled();
  expect(screen.queryByRole("button", { name: "Change" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Send to Recipient" }));
  await screen.findByRole("status");
  expect(send.mock.calls[0][0]).toEqual(send.mock.calls[1][0]);
  expect(onSent).toHaveBeenCalledTimes(1);
});
it("does not announce success when the server refuses the last copy", async () => {
  send.mockResolvedValue({ ok: false, error: "no_spare" });
  const onSent = vi.fn();
  render(wrap(<GiftSpareDialog card={card} onClose={() => {}} onSent={onSent} />));
  fireEvent.change(screen.getByRole("textbox"), { target: { value: "Reci" } });
  fireEvent.click(await screen.findByRole("button", { name: "Recipient" }));
  fireEvent.click(screen.getByRole("button", { name: "Send to Recipient" }));
  expect((await screen.findByRole("alert")).textContent).toContain("no longer have a spare");
  expect(onSent).not.toHaveBeenCalled();
});
it("shows incoming gifts, refreshes the collection once, and dismisses only those receipts", async () => {
  inbox.mockResolvedValue({ gifts: [{ id: 9, sender: recipient, card }], total: 1 });
  dismiss.mockResolvedValue({ gifts: [], total: 0 });
  const onReceived = vi.fn();
  render(wrap(<GiftInbox onReceived={onReceived} />));
  fireEvent.click(await screen.findByRole("button", { name: "Gifts (1)" }));
  expect(screen.getByText("Recipient")).toBeTruthy();
  expect(onReceived).toHaveBeenCalledTimes(1);
  fireEvent.focus(window);
  await waitFor(() => expect(inbox).toHaveBeenCalledTimes(2));
  expect(onReceived).toHaveBeenCalledTimes(1);
  expect(screen.getByText("It's already in your collection.")).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Ok" }));
  await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull());
  expect(dismiss).toHaveBeenCalledWith({ data: { ids: [9] } });
});
it("adds no toolbar button when there are no incoming gifts", async () => {
  inbox.mockResolvedValue({ gifts: [], total: 0 });
  render(wrap(<GiftInbox onReceived={() => {}} />));
  await waitFor(() => expect(inbox).toHaveBeenCalled());
  expect(screen.queryByRole("button")).toBeNull();
});
