// Generates src/lib/country-names-zh.generated.ts: Simplified Chinese names
// for every country, region and the Global scope the site can display.
// Regenerate with: npm run i18n:build-country-names (vite-node, because
// country.ts uses extensionless relative imports plain node cannot resolve).
//
// A build-time table instead of runtime Intl.DisplayNames on purpose: the
// server's ICU and a visitor's browser ICU can disagree on region names,
// which would hydrate a mismatch. Baking one snapshot keeps SSR and client
// byte-identical everywhere.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { COUNTRY_OPTIONS, GLOBAL_SCOPE_CODE } from "../src/lib/country";
import { REGION_DEFS } from "../src/lib/regions.generated";

const display = new Intl.DisplayNames(["zh-Hans"], { type: "region" });

// The site's region codes are its own; their zh names come from the UN M49
// area codes Intl understands. Middle East has no M49 code, so it is
// hand-labeled.
const REGION_M49: Record<string, string> = {
  Africa: "002",
  Americas: "019",
  Asia: "142",
  Caribbean: "029",
  "Central America": "013",
  "Central Asia": "143",
  "East Asia": "030",
  "Eastern Africa": "014",
  "Eastern Europe": "151",
  Europe: "150",
  "Middle Africa": "017",
  "North America": "021",
  "Northern Africa": "015",
  "Northern Europe": "154",
  Oceania: "009",
  "South America": "005",
  "Southeast Asia": "035",
  "Southern Africa": "018",
  "Southern Asia": "034",
  "Southern Europe": "039",
  "Western Africa": "011",
  "Western Europe": "155",
};
const REGION_HAND_LABELED: Record<string, string> = {
  "Middle East": "中东",
};

const entries: [string, string][] = [[GLOBAL_SCOPE_CODE, "全球"]];

for (const { code, name } of COUNTRY_OPTIONS) {
  const zh = display.of(code);
  // Intl echoes the code back for anything it cannot name; keep English
  // (via fallback at read time) rather than shipping a code as a "name".
  if (!zh || zh === code) {
    console.warn(`no zh name for country ${code} (${name}), will fall back to English`);
    continue;
  }
  entries.push([code, zh]);
}

for (const region of REGION_DEFS) {
  const hand = REGION_HAND_LABELED[region.name];
  const m49 = REGION_M49[region.name];
  const zh = hand ?? (m49 ? display.of(m49) : null);
  if (!zh || zh === m49) {
    console.warn(`no zh name for region ${region.code} (${region.name}), will fall back to English`);
    continue;
  }
  entries.push([region.code, zh]);
}

const body = entries.map(([code, zh]) => `  "${code}": "${zh}",`).join("\n");
const output = `// Generated by scripts/generate-country-names-zh.ts - do not edit by hand.
// Simplified Chinese display names for country codes, region codes and the
// Global scope, snapshotted from Node's ICU so SSR and browsers agree.
// Regenerate with: npm run i18n:build-country-names

export const COUNTRY_NAMES_ZH: Record<string, string> = {
${body}
};
`;

const target = fileURLToPath(new URL("../src/lib/country-names-zh.generated.ts", import.meta.url));
writeFileSync(target, output);
console.log(`wrote ${entries.length} names to src/lib/country-names-zh.generated.ts`);
