// Generates src/lib/country-names-es.generated.ts: neutral Latin American
// Spanish names for every country, region and the Global scope the site can
// display. Regenerate with: npm run i18n:build-country-names:es (vite-node,
// because country.ts uses extensionless relative imports plain node cannot
// resolve).
//
// A build-time table instead of runtime Intl.DisplayNames on purpose: the
// server's ICU and a visitor's browser ICU can disagree on region names,
// which would hydrate a mismatch. Baking one snapshot keeps SSR and client
// byte-identical everywhere.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { COUNTRY_OPTIONS, GLOBAL_SCOPE_CODE } from "../src/lib/country";
import { REGION_DEFS } from "../src/lib/regions.generated";

const display = new Intl.DisplayNames(["es-419"], { type: "region" });

// The site's region codes are its own; their Spanish names come from the UN
// M49 area codes Intl understands. Middle East has no M49 code, so it is
// hand-labeled in the Latin American form used by this catalog.
const REGION_M49: Record<string, string> = {
  Africa: "002",
  Americas: "019",
  Asia: "142",
  Caribbean: "029",
  "Central America": "013",
  "Central Asia": "143",
  "East Asia": "030",
  "Eastern Africa": "014",
  "Eastern Europe": "151",
  Europe: "150",
  "Middle Africa": "017",
  "North America": "021",
  "Northern Africa": "015",
  "Northern Europe": "154",
  Oceania: "009",
  "South America": "005",
  "Southeast Asia": "035",
  "Southern Africa": "018",
  "Southern Asia": "034",
  "Southern Europe": "039",
  "Western Africa": "011",
  "Western Europe": "155",
};
const REGION_HAND_LABELED: Record<string, string> = {
  "Middle East": "Medio Oriente",
};

const entries: [string, string][] = [[GLOBAL_SCOPE_CODE, "Global"]];

for (const { code, name } of COUNTRY_OPTIONS) {
  const es = display.of(code);
  // Intl echoes the code back for anything it cannot name; keep English
  // (via fallback at read time) rather than shipping a code as a "name".
  if (!es || es === code) {
    console.warn(`no es name for country ${code} (${name}), will fall back to English`);
    continue;
  }
  entries.push([code, es]);
}

for (const region of REGION_DEFS) {
  const hand = REGION_HAND_LABELED[region.name];
  const m49 = REGION_M49[region.name];
  const es = hand ?? (m49 ? display.of(m49) : null);
  if (!es || es === m49) {
    console.warn(`no es name for region ${region.code} (${region.name}), will fall back to English`);
    continue;
  }
  entries.push([region.code, es]);
}

const body = entries.map(([code, es]) => `  "${code}": ${JSON.stringify(es)},`).join("\n");
const output = `// Generated by scripts/generate-country-names-es.ts - do not edit by hand.
// Neutral Latin American Spanish display names for country codes, region codes
// and the Global scope, snapshotted from Node's ICU so SSR and browsers agree.
// Regenerate with: npm run i18n:build-country-names:es

export const COUNTRY_NAMES_ES: Record<string, string> = {
${body}
};
`;

const target = fileURLToPath(new URL("../src/lib/country-names-es.generated.ts", import.meta.url));
writeFileSync(target, output);
console.log(`wrote ${entries.length} names to src/lib/country-names-es.generated.ts`);
// Vite's project config can leave plugin handles open after a one-shot
// vite-node script. The snapshot is written synchronously, so finish here.
process.exit(0);
