/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PopoffsRouteImport } from './routes/popoffs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerUsernameRouteImport } from './routes/player/$username'

const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PopoffsRoute = PopoffsRouteImport.update({
  id: '/popoffs',
  path: '/popoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUsernameRoute = PlayerUsernameRouteImport.update({
  id: '/player/$username',
  path: '/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/popoffs': typeof PopoffsRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/scores': typeof ScoresRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/popoffs': typeof PopoffsRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/scores': typeof ScoresRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/popoffs': typeof PopoffsRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/scores': typeof ScoresRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/popoffs'
    | '/rankings'
    | '/replay'
    | '/scores'
    | '/player/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/popoffs'
    | '/rankings'
    | '/replay'
    | '/scores'
    | '/player/$username'
  id:
    | '__root__'
    | '/'
    | '/popoffs'
    | '/rankings'
    | '/replay'
    | '/scores'
    | '/player/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PopoffsRoute: typeof PopoffsRoute
  RankingsRoute: typeof RankingsRoute
  ReplayRoute: typeof ReplayRoute
  ScoresRoute: typeof ScoresRoute
  PlayerUsernameRoute: typeof PlayerUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popoffs': {
      id: '/popoffs'
      path: '/popoffs'
      fullPath: '/popoffs'
      preLoaderRoute: typeof PopoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$username': {
      id: '/player/$username'
      path: '/player/$username'
      fullPath: '/player/$username'
      preLoaderRoute: typeof PlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PopoffsRoute: PopoffsRoute,
  RankingsRoute: RankingsRoute,
  ReplayRoute: ReplayRoute,
  ScoresRoute: ScoresRoute,
  PlayerUsernameRoute: PlayerUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
