/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TopPlaysRouteImport } from './routes/top-plays'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SnipesRouteImport } from './routes/snipes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FarmHelperRouteImport } from './routes/farm-helper'
import { Route as BbcodeRouteImport } from './routes/bbcode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerUsernameRouteImport } from './routes/player/$username'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiReplayUploadRouteImport } from './routes/api/replay-upload'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiFaviconRouteImport } from './routes/api/favicon'
import { Route as ApiBackgroundRouteImport } from './routes/api/background'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiAudioRouteImport } from './routes/api/audio'
import { Route as AdminR2RouteImport } from './routes/admin/r2'
import { Route as AdminOgPreviewRouteImport } from './routes/admin/og-preview'
import { Route as AdminMonitorRouteImport } from './routes/admin/monitor'
import { Route as AdminLiveBackendRouteImport } from './routes/admin/live-backend'
import { Route as AdminDanClassifierRouteImport } from './routes/admin/dan-classifier'
import { Route as VideosIdFilenameRouteImport } from './routes/videos/$id/$filename'
import { Route as PlayerUsernameRecentRouteImport } from './routes/player/$username/recent'
import { Route as PlayerUsernameManiacardRouteImport } from './routes/player/$username/maniacard'
import { Route as PlayerUsernameActivityRouteImport } from './routes/player/$username/activity'
import { Route as PlayerUsernameAboutRouteImport } from './routes/player/$username/about'
import { Route as FarmHelperMapBeatmapIdRouteImport } from './routes/farm-helper/map/$beatmapId'
import { Route as ApiAuthOsuRouteImport } from './routes/api/auth/osu'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthOsuCallbackRouteImport } from './routes/api/auth/osu/callback'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TopPlaysRoute = TopPlaysRouteImport.update({
  id: '/top-plays',
  path: '/top-plays',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SnipesRoute = SnipesRouteImport.update({
  id: '/snipes',
  path: '/snipes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmHelperRoute = FarmHelperRouteImport.update({
  id: '/farm-helper',
  path: '/farm-helper',
  getParentRoute: () => rootRouteImport,
} as any)
const BbcodeRoute = BbcodeRouteImport.update({
  id: '/bbcode',
  path: '/bbcode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUsernameRoute = PlayerUsernameRouteImport.update({
  id: '/player/$username',
  path: '/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReplayUploadRoute = ApiReplayUploadRouteImport.update({
  id: '/api/replay-upload',
  path: '/api/replay-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackgroundRoute = ApiBackgroundRouteImport.update({
  id: '/api/background',
  path: '/api/background',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminR2Route = AdminR2RouteImport.update({
  id: '/admin/r2',
  path: '/admin/r2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOgPreviewRoute = AdminOgPreviewRouteImport.update({
  id: '/admin/og-preview',
  path: '/admin/og-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitorRoute = AdminMonitorRouteImport.update({
  id: '/admin/monitor',
  path: '/admin/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveBackendRoute = AdminLiveBackendRouteImport.update({
  id: '/admin/live-backend',
  path: '/admin/live-backend',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDanClassifierRoute = AdminDanClassifierRouteImport.update({
  id: '/admin/dan-classifier',
  path: '/admin/dan-classifier',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdFilenameRoute = VideosIdFilenameRouteImport.update({
  id: '/videos/$id/$filename',
  path: '/videos/$id/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUsernameRecentRoute = PlayerUsernameRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => PlayerUsernameRoute,
} as any)
const PlayerUsernameManiacardRoute = PlayerUsernameManiacardRouteImport.update({
  id: '/maniacard',
  path: '/maniacard',
  getParentRoute: () => PlayerUsernameRoute,
} as any)
const PlayerUsernameActivityRoute = PlayerUsernameActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PlayerUsernameRoute,
} as any)
const PlayerUsernameAboutRoute = PlayerUsernameAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PlayerUsernameRoute,
} as any)
const FarmHelperMapBeatmapIdRoute = FarmHelperMapBeatmapIdRouteImport.update({
  id: '/map/$beatmapId',
  path: '/map/$beatmapId',
  getParentRoute: () => FarmHelperRoute,
} as any)
const ApiAuthOsuRoute = ApiAuthOsuRouteImport.update({
  id: '/api/auth/osu',
  path: '/api/auth/osu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOsuCallbackRoute = ApiAuthOsuCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthOsuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bbcode': typeof BbcodeRoute
  '/farm-helper': typeof FarmHelperRouteWithChildren
  '/legal': typeof LegalRoute
  '/maps': typeof MapsRoute
  '/packs': typeof PacksRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/snipes': typeof SnipesRoute
  '/terms': typeof TermsRoute
  '/top-plays': typeof TopPlaysRoute
  '/tracker': typeof TrackerRoute
  '/admin/dan-classifier': typeof AdminDanClassifierRoute
  '/admin/live-backend': typeof AdminLiveBackendRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/og-preview': typeof AdminOgPreviewRoute
  '/admin/r2': typeof AdminR2Route
  '/api/audio': typeof ApiAudioRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/background': typeof ApiBackgroundRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/og': typeof ApiOgRoute
  '/api/replay-upload': typeof ApiReplayUploadRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/sync': typeof ApiSyncRoute
  '/player/$username': typeof PlayerUsernameRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/osu': typeof ApiAuthOsuRouteWithChildren
  '/farm-helper/map/$beatmapId': typeof FarmHelperMapBeatmapIdRoute
  '/player/$username/about': typeof PlayerUsernameAboutRoute
  '/player/$username/activity': typeof PlayerUsernameActivityRoute
  '/player/$username/maniacard': typeof PlayerUsernameManiacardRoute
  '/player/$username/recent': typeof PlayerUsernameRecentRoute
  '/videos/$id/$filename': typeof VideosIdFilenameRoute
  '/api/auth/osu/callback': typeof ApiAuthOsuCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bbcode': typeof BbcodeRoute
  '/farm-helper': typeof FarmHelperRouteWithChildren
  '/legal': typeof LegalRoute
  '/maps': typeof MapsRoute
  '/packs': typeof PacksRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/snipes': typeof SnipesRoute
  '/terms': typeof TermsRoute
  '/top-plays': typeof TopPlaysRoute
  '/tracker': typeof TrackerRoute
  '/admin/dan-classifier': typeof AdminDanClassifierRoute
  '/admin/live-backend': typeof AdminLiveBackendRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/og-preview': typeof AdminOgPreviewRoute
  '/admin/r2': typeof AdminR2Route
  '/api/audio': typeof ApiAudioRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/background': typeof ApiBackgroundRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/og': typeof ApiOgRoute
  '/api/replay-upload': typeof ApiReplayUploadRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/sync': typeof ApiSyncRoute
  '/player/$username': typeof PlayerUsernameRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/osu': typeof ApiAuthOsuRouteWithChildren
  '/farm-helper/map/$beatmapId': typeof FarmHelperMapBeatmapIdRoute
  '/player/$username/about': typeof PlayerUsernameAboutRoute
  '/player/$username/activity': typeof PlayerUsernameActivityRoute
  '/player/$username/maniacard': typeof PlayerUsernameManiacardRoute
  '/player/$username/recent': typeof PlayerUsernameRecentRoute
  '/videos/$id/$filename': typeof VideosIdFilenameRoute
  '/api/auth/osu/callback': typeof ApiAuthOsuCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bbcode': typeof BbcodeRoute
  '/farm-helper': typeof FarmHelperRouteWithChildren
  '/legal': typeof LegalRoute
  '/maps': typeof MapsRoute
  '/packs': typeof PacksRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/snipes': typeof SnipesRoute
  '/terms': typeof TermsRoute
  '/top-plays': typeof TopPlaysRoute
  '/tracker': typeof TrackerRoute
  '/admin/dan-classifier': typeof AdminDanClassifierRoute
  '/admin/live-backend': typeof AdminLiveBackendRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/og-preview': typeof AdminOgPreviewRoute
  '/admin/r2': typeof AdminR2Route
  '/api/audio': typeof ApiAudioRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/background': typeof ApiBackgroundRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/og': typeof ApiOgRoute
  '/api/replay-upload': typeof ApiReplayUploadRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/sync': typeof ApiSyncRoute
  '/player/$username': typeof PlayerUsernameRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/osu': typeof ApiAuthOsuRouteWithChildren
  '/farm-helper/map/$beatmapId': typeof FarmHelperMapBeatmapIdRoute
  '/player/$username/about': typeof PlayerUsernameAboutRoute
  '/player/$username/activity': typeof PlayerUsernameActivityRoute
  '/player/$username/maniacard': typeof PlayerUsernameManiacardRoute
  '/player/$username/recent': typeof PlayerUsernameRecentRoute
  '/videos/$id/$filename': typeof VideosIdFilenameRoute
  '/api/auth/osu/callback': typeof ApiAuthOsuCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bbcode'
    | '/farm-helper'
    | '/legal'
    | '/maps'
    | '/packs'
    | '/privacy'
    | '/rankings'
    | '/replay'
    | '/settings'
    | '/snipes'
    | '/terms'
    | '/top-plays'
    | '/tracker'
    | '/admin/dan-classifier'
    | '/admin/live-backend'
    | '/admin/monitor'
    | '/admin/og-preview'
    | '/admin/r2'
    | '/api/audio'
    | '/api/avatar'
    | '/api/background'
    | '/api/favicon'
    | '/api/og'
    | '/api/replay-upload'
    | '/api/sitemap'
    | '/api/sync'
    | '/player/$username'
    | '/api/auth/logout'
    | '/api/auth/osu'
    | '/farm-helper/map/$beatmapId'
    | '/player/$username/about'
    | '/player/$username/activity'
    | '/player/$username/maniacard'
    | '/player/$username/recent'
    | '/videos/$id/$filename'
    | '/api/auth/osu/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bbcode'
    | '/farm-helper'
    | '/legal'
    | '/maps'
    | '/packs'
    | '/privacy'
    | '/rankings'
    | '/replay'
    | '/settings'
    | '/snipes'
    | '/terms'
    | '/top-plays'
    | '/tracker'
    | '/admin/dan-classifier'
    | '/admin/live-backend'
    | '/admin/monitor'
    | '/admin/og-preview'
    | '/admin/r2'
    | '/api/audio'
    | '/api/avatar'
    | '/api/background'
    | '/api/favicon'
    | '/api/og'
    | '/api/replay-upload'
    | '/api/sitemap'
    | '/api/sync'
    | '/player/$username'
    | '/api/auth/logout'
    | '/api/auth/osu'
    | '/farm-helper/map/$beatmapId'
    | '/player/$username/about'
    | '/player/$username/activity'
    | '/player/$username/maniacard'
    | '/player/$username/recent'
    | '/videos/$id/$filename'
    | '/api/auth/osu/callback'
  id:
    | '__root__'
    | '/'
    | '/bbcode'
    | '/farm-helper'
    | '/legal'
    | '/maps'
    | '/packs'
    | '/privacy'
    | '/rankings'
    | '/replay'
    | '/settings'
    | '/snipes'
    | '/terms'
    | '/top-plays'
    | '/tracker'
    | '/admin/dan-classifier'
    | '/admin/live-backend'
    | '/admin/monitor'
    | '/admin/og-preview'
    | '/admin/r2'
    | '/api/audio'
    | '/api/avatar'
    | '/api/background'
    | '/api/favicon'
    | '/api/og'
    | '/api/replay-upload'
    | '/api/sitemap'
    | '/api/sync'
    | '/player/$username'
    | '/api/auth/logout'
    | '/api/auth/osu'
    | '/farm-helper/map/$beatmapId'
    | '/player/$username/about'
    | '/player/$username/activity'
    | '/player/$username/maniacard'
    | '/player/$username/recent'
    | '/videos/$id/$filename'
    | '/api/auth/osu/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BbcodeRoute: typeof BbcodeRoute
  FarmHelperRoute: typeof FarmHelperRouteWithChildren
  LegalRoute: typeof LegalRoute
  MapsRoute: typeof MapsRoute
  PacksRoute: typeof PacksRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingsRoute: typeof RankingsRoute
  ReplayRoute: typeof ReplayRoute
  SettingsRoute: typeof SettingsRoute
  SnipesRoute: typeof SnipesRoute
  TermsRoute: typeof TermsRoute
  TopPlaysRoute: typeof TopPlaysRoute
  TrackerRoute: typeof TrackerRoute
  AdminDanClassifierRoute: typeof AdminDanClassifierRoute
  AdminLiveBackendRoute: typeof AdminLiveBackendRoute
  AdminMonitorRoute: typeof AdminMonitorRoute
  AdminOgPreviewRoute: typeof AdminOgPreviewRoute
  AdminR2Route: typeof AdminR2Route
  ApiAudioRoute: typeof ApiAudioRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiBackgroundRoute: typeof ApiBackgroundRoute
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiReplayUploadRoute: typeof ApiReplayUploadRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiSyncRoute: typeof ApiSyncRoute
  PlayerUsernameRoute: typeof PlayerUsernameRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthOsuRoute: typeof ApiAuthOsuRouteWithChildren
  VideosIdFilenameRoute: typeof VideosIdFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-plays': {
      id: '/top-plays'
      path: '/top-plays'
      fullPath: '/top-plays'
      preLoaderRoute: typeof TopPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snipes': {
      id: '/snipes'
      path: '/snipes'
      fullPath: '/snipes'
      preLoaderRoute: typeof SnipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-helper': {
      id: '/farm-helper'
      path: '/farm-helper'
      fullPath: '/farm-helper'
      preLoaderRoute: typeof FarmHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbcode': {
      id: '/bbcode'
      path: '/bbcode'
      fullPath: '/bbcode'
      preLoaderRoute: typeof BbcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$username': {
      id: '/player/$username'
      path: '/player/$username'
      fullPath: '/player/$username'
      preLoaderRoute: typeof PlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/replay-upload': {
      id: '/api/replay-upload'
      path: '/api/replay-upload'
      fullPath: '/api/replay-upload'
      preLoaderRoute: typeof ApiReplayUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/background': {
      id: '/api/background'
      path: '/api/background'
      fullPath: '/api/background'
      preLoaderRoute: typeof ApiBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/r2': {
      id: '/admin/r2'
      path: '/admin/r2'
      fullPath: '/admin/r2'
      preLoaderRoute: typeof AdminR2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/og-preview': {
      id: '/admin/og-preview'
      path: '/admin/og-preview'
      fullPath: '/admin/og-preview'
      preLoaderRoute: typeof AdminOgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitor': {
      id: '/admin/monitor'
      path: '/admin/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AdminMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live-backend': {
      id: '/admin/live-backend'
      path: '/admin/live-backend'
      fullPath: '/admin/live-backend'
      preLoaderRoute: typeof AdminLiveBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dan-classifier': {
      id: '/admin/dan-classifier'
      path: '/admin/dan-classifier'
      fullPath: '/admin/dan-classifier'
      preLoaderRoute: typeof AdminDanClassifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id/$filename': {
      id: '/videos/$id/$filename'
      path: '/videos/$id/$filename'
      fullPath: '/videos/$id/$filename'
      preLoaderRoute: typeof VideosIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$username/recent': {
      id: '/player/$username/recent'
      path: '/recent'
      fullPath: '/player/$username/recent'
      preLoaderRoute: typeof PlayerUsernameRecentRouteImport
      parentRoute: typeof PlayerUsernameRoute
    }
    '/player/$username/maniacard': {
      id: '/player/$username/maniacard'
      path: '/maniacard'
      fullPath: '/player/$username/maniacard'
      preLoaderRoute: typeof PlayerUsernameManiacardRouteImport
      parentRoute: typeof PlayerUsernameRoute
    }
    '/player/$username/activity': {
      id: '/player/$username/activity'
      path: '/activity'
      fullPath: '/player/$username/activity'
      preLoaderRoute: typeof PlayerUsernameActivityRouteImport
      parentRoute: typeof PlayerUsernameRoute
    }
    '/player/$username/about': {
      id: '/player/$username/about'
      path: '/about'
      fullPath: '/player/$username/about'
      preLoaderRoute: typeof PlayerUsernameAboutRouteImport
      parentRoute: typeof PlayerUsernameRoute
    }
    '/farm-helper/map/$beatmapId': {
      id: '/farm-helper/map/$beatmapId'
      path: '/map/$beatmapId'
      fullPath: '/farm-helper/map/$beatmapId'
      preLoaderRoute: typeof FarmHelperMapBeatmapIdRouteImport
      parentRoute: typeof FarmHelperRoute
    }
    '/api/auth/osu': {
      id: '/api/auth/osu'
      path: '/api/auth/osu'
      fullPath: '/api/auth/osu'
      preLoaderRoute: typeof ApiAuthOsuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/osu/callback': {
      id: '/api/auth/osu/callback'
      path: '/callback'
      fullPath: '/api/auth/osu/callback'
      preLoaderRoute: typeof ApiAuthOsuCallbackRouteImport
      parentRoute: typeof ApiAuthOsuRoute
    }
  }
}

interface FarmHelperRouteChildren {
  FarmHelperMapBeatmapIdRoute: typeof FarmHelperMapBeatmapIdRoute
}

const FarmHelperRouteChildren: FarmHelperRouteChildren = {
  FarmHelperMapBeatmapIdRoute: FarmHelperMapBeatmapIdRoute,
}

const FarmHelperRouteWithChildren = FarmHelperRoute._addFileChildren(
  FarmHelperRouteChildren,
)

interface PlayerUsernameRouteChildren {
  PlayerUsernameAboutRoute: typeof PlayerUsernameAboutRoute
  PlayerUsernameActivityRoute: typeof PlayerUsernameActivityRoute
  PlayerUsernameManiacardRoute: typeof PlayerUsernameManiacardRoute
  PlayerUsernameRecentRoute: typeof PlayerUsernameRecentRoute
}

const PlayerUsernameRouteChildren: PlayerUsernameRouteChildren = {
  PlayerUsernameAboutRoute: PlayerUsernameAboutRoute,
  PlayerUsernameActivityRoute: PlayerUsernameActivityRoute,
  PlayerUsernameManiacardRoute: PlayerUsernameManiacardRoute,
  PlayerUsernameRecentRoute: PlayerUsernameRecentRoute,
}

const PlayerUsernameRouteWithChildren = PlayerUsernameRoute._addFileChildren(
  PlayerUsernameRouteChildren,
)

interface ApiAuthOsuRouteChildren {
  ApiAuthOsuCallbackRoute: typeof ApiAuthOsuCallbackRoute
}

const ApiAuthOsuRouteChildren: ApiAuthOsuRouteChildren = {
  ApiAuthOsuCallbackRoute: ApiAuthOsuCallbackRoute,
}

const ApiAuthOsuRouteWithChildren = ApiAuthOsuRoute._addFileChildren(
  ApiAuthOsuRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BbcodeRoute: BbcodeRoute,
  FarmHelperRoute: FarmHelperRouteWithChildren,
  LegalRoute: LegalRoute,
  MapsRoute: MapsRoute,
  PacksRoute: PacksRoute,
  PrivacyRoute: PrivacyRoute,
  RankingsRoute: RankingsRoute,
  ReplayRoute: ReplayRoute,
  SettingsRoute: SettingsRoute,
  SnipesRoute: SnipesRoute,
  TermsRoute: TermsRoute,
  TopPlaysRoute: TopPlaysRoute,
  TrackerRoute: TrackerRoute,
  AdminDanClassifierRoute: AdminDanClassifierRoute,
  AdminLiveBackendRoute: AdminLiveBackendRoute,
  AdminMonitorRoute: AdminMonitorRoute,
  AdminOgPreviewRoute: AdminOgPreviewRoute,
  AdminR2Route: AdminR2Route,
  ApiAudioRoute: ApiAudioRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiBackgroundRoute: ApiBackgroundRoute,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiOgRoute: ApiOgRoute,
  ApiReplayUploadRoute: ApiReplayUploadRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiSyncRoute: ApiSyncRoute,
  PlayerUsernameRoute: PlayerUsernameRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthOsuRoute: ApiAuthOsuRouteWithChildren,
  VideosIdFilenameRoute: VideosIdFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
