/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TopPlaysRouteImport } from './routes/top-plays'
import { Route as SnipesRouteImport } from './routes/snipes'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerUsernameRouteImport } from './routes/player/$username'
import { Route as ApiAudioRouteImport } from './routes/api/audio'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TopPlaysRoute = TopPlaysRouteImport.update({
  id: '/top-plays',
  path: '/top-plays',
  getParentRoute: () => rootRouteImport,
} as any)
const SnipesRoute = SnipesRouteImport.update({
  id: '/snipes',
  path: '/snipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUsernameRoute = PlayerUsernameRouteImport.update({
  id: '/player/$username',
  path: '/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/snipes': typeof SnipesRoute
  '/top-plays': typeof TopPlaysRoute
  '/tracker': typeof TrackerRoute
  '/api/audio': typeof ApiAudioRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/snipes': typeof SnipesRoute
  '/top-plays': typeof TopPlaysRoute
  '/tracker': typeof TrackerRoute
  '/api/audio': typeof ApiAudioRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/replay': typeof ReplayRoute
  '/snipes': typeof SnipesRoute
  '/top-plays': typeof TopPlaysRoute
  '/tracker': typeof TrackerRoute
  '/api/audio': typeof ApiAudioRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rankings'
    | '/replay'
    | '/snipes'
    | '/top-plays'
    | '/tracker'
    | '/api/audio'
    | '/player/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rankings'
    | '/replay'
    | '/snipes'
    | '/top-plays'
    | '/tracker'
    | '/api/audio'
    | '/player/$username'
  id:
    | '__root__'
    | '/'
    | '/rankings'
    | '/replay'
    | '/snipes'
    | '/top-plays'
    | '/tracker'
    | '/api/audio'
    | '/player/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingsRoute: typeof RankingsRoute
  ReplayRoute: typeof ReplayRoute
  SnipesRoute: typeof SnipesRoute
  TopPlaysRoute: typeof TopPlaysRoute
  TrackerRoute: typeof TrackerRoute
  ApiAudioRoute: typeof ApiAudioRoute
  PlayerUsernameRoute: typeof PlayerUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-plays': {
      id: '/top-plays'
      path: '/top-plays'
      fullPath: '/top-plays'
      preLoaderRoute: typeof TopPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snipes': {
      id: '/snipes'
      path: '/snipes'
      fullPath: '/snipes'
      preLoaderRoute: typeof SnipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$username': {
      id: '/player/$username'
      path: '/player/$username'
      fullPath: '/player/$username'
      preLoaderRoute: typeof PlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingsRoute: RankingsRoute,
  ReplayRoute: ReplayRoute,
  SnipesRoute: SnipesRoute,
  TopPlaysRoute: TopPlaysRoute,
  TrackerRoute: TrackerRoute,
  ApiAudioRoute: ApiAudioRoute,
  PlayerUsernameRoute: PlayerUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
