// Debug output of the family scorer: every gate and term value, and a per-family
// list of the main contributions with a one-line description each. None of this
// feeds a rating. The contribution lists are a partial breakdown for reading a
// verdict; they skip some terms, the LN nerf and the practice-pattern trim, so
// they do not sum to the final family score.

import type { ScoringTerms } from "./scoring-terms";
import type { DanScoreContribution, DanSkillFamily } from "./types";

// The main per-family bonuses computed in scoring.ts.
export interface FamilyBonuses {
  jackBonus: number;
  streamBonus: number;
  jumpstreamBonus: number;
  staminaBonus: number;
  handstreamBonus: number;
  chordjackBonus: number;
  techBonus: number;
}

export type PracticeFamily = "jack" | "stream" | "jumpstream" | "handstream" | "stamina" | "chordjack" | "tech";

// The practice-pattern inflation trim per family: its 0-1 gate and the SR it removed.
export interface PracticeInflation {
  gates: Record<PracticeFamily, number>;
  compressions: Record<PracticeFamily, number>;
}

type DebugTerms = ScoringTerms & FamilyBonuses;

export function scoringDebugGates(t: DebugTerms, practice: PracticeInflation): Record<string, number> {
  return {
    chordGate: t.chordGate,
    chordedSpeedGate: t.chordedSpeedGate,
    denseChordedSpeedGate: t.denseChordedSpeedGate,
    highChordGate: t.highChordGate,
    denseChordWallGate: t.denseChordWallGate,
    denseJackFileGate: t.denseJackFileGate,
    denseWallJackGate: t.denseWallJackGate,
    compactJackUnderrateGate: t.compactJackUnderrateGate,
    slowRepetitiveJackstreamGate: t.slowRepetitiveJackstreamGate,
    ratedRepetitiveSpeedjackGate: t.ratedRepetitiveSpeedjackGate,
    handstreamChordGate: t.handstreamChordGate,
    jumpstreamChordGate: t.jumpstreamChordGate,
    pureSpeedGate: t.pureSpeedGate,
    speedGate: t.speedGate,
    sustainedLightJumpstreamGate: t.sustainedLightJumpstreamGate,
    chordjackEnduranceGate: t.chordjackEnduranceGate,
    strongJackGate: t.strongJackGate,
    etaJackPressureGate: t.etaJackPressureGate,
    steadySpeedMapGate: t.steadySpeedMapGate,
    longEnduranceMapGate: t.longEnduranceMapGate,
    longSparseJackDropMapGate: t.longSparseJackDropMapGate,
    longMidChordStaminaMapGate: t.longMidChordStaminaMapGate,
    fastLongMidChordStaminaGate: t.fastLongMidChordStaminaGate,
    jackyLongMidChordStaminaGate: t.jackyLongMidChordStaminaGate,
    denseChordStaminaOverrateGate: t.denseChordStaminaOverrateGate,
    moderateChordSteadyStreamStructuralGate: t.moderateChordSteadyStreamStructuralGate,
    compactHandstreamStaminaStructuralGate: t.compactHandstreamStaminaStructuralGate,
    shortSimpleChordjackWallStructuralGate: t.shortSimpleChordjackWallStructuralGate,
    longJumpstreamStaminaCompressionGate: t.longJumpstreamStaminaCompression > 0 ? t.longJumpstreamStaminaCompression / 0.38 : 0,
    simpleLongJumpstreamPatternCompressionGate: t.simpleLongJumpstreamPatternCompression > 0 ? t.simpleLongJumpstreamPatternCompression / 0.11 : 0,
    shortLnHybridStructuralGate: t.shortLnHybridStructuralGate,
    lowChordSteadySpeedStructuralGate: t.lowChordSteadySpeedStructuralGate,
    compactTechnicalFlowStructuralGate: t.compactTechnicalFlowStructuralGate,
    compactChordWallStructuralGate: t.compactChordWallStructuralGate,
    simpleDenseChordWallStructuralGate: t.simpleDenseChordWallStructuralGate,
    lowRateDenseChordWallGate: t.lowRateDenseChordWallGate,
    variedLowRateDenseChordWallGate: t.variedLowRateDenseChordWallGate,
    simpleMidHighChordWallStructuralGate: t.simpleMidHighChordWallStructuralGate,
    awkwardMidRateChordjackWallGate: t.awkwardMidRateChordjackWallGate,
    midHighChordSustainedTechStructuralGate: t.midHighChordSustainedTechStructuralGate,
    marathonTechnicalEnduranceGate: t.marathonTechnicalEnduranceGate,
    lowSrShortDenseWallCompressionGate: t.lowSrShortDenseWallCompression > 0 ? t.lowSrShortDenseWallCompression / 0.32 : 0,
    midChordSpeedjackGate: t.midChordSpeedjackGate,
    compactPureChordjackStaminaGate: t.compactPureChordjackStaminaGate,
    shortHighChordWallStructuralGate: t.shortHighChordWallStructuralCompression > 0 ? t.shortHighChordWallStructuralCompression / 0.63 : 0,
    farmJumptrillGate: t.farmJumptrillGate,
    ratedVibroJumptrillGate: t.ratedVibroJumptrillGate,
    lowSrTechnicalRhythmGate: t.lowSrTechnicalRhythmGate,
    highRatePackTechnicalRhythmInflationGate: t.highRatePackTechnicalRhythmInflationGate,
    compactDeltaSpeedBridgeGate: t.compactDeltaSpeedBridgeGate,
    ratePackTechShapeGate: t.ratePackTechShapeGate,
    syncopatedChordTechGate: t.syncopatedChordTechGate,
    compactChordSwitchTechGate: t.compactChordSwitchTechGate,
    technicalAnchorGate: t.technicalAnchorGate,
    compactTechnicalMarathonGate: t.compactTechnicalMarathonGate,
    shortSpikeGate: t.shortSpikeGate,
    localizedJumptrillSpikeGate: t.localizedJumptrillSpikeGate,
    lowMidSustainedPressureGate: t.lowMidSustainedPressureGate,
    sustainedHighChordWallGate: t.sustainedHighChordWallGate,
    jackPracticePatternInflationGate: practice.gates.jack,
    streamPracticePatternInflationGate: practice.gates.stream,
    jumpstreamPracticePatternInflationGate: practice.gates.jumpstream,
    handstreamPracticePatternInflationGate: practice.gates.handstream,
    staminaPracticePatternInflationGate: practice.gates.stamina,
    chordjackPracticePatternInflationGate: practice.gates.chordjack,
    techPracticePatternInflationGate: practice.gates.tech,
  };
}

export function scoringDebugTerms(t: DebugTerms, practice: PracticeInflation): Record<string, number> {
  return {
    speedBonus: t.speedBonus,
    pureSpeedBonus: t.pureSpeedBonus,
    lowChordSustainedSpeedBonus: t.lowChordSustainedSpeedBonus,
    longLowChordSpeedBonus: t.longLowChordSpeedBonus,
    lightChordGammaSpeedFloorBonus: t.lightChordGammaSpeedFloorBonus,
    lowSrSpeedUnderrateBonus: t.lowSrSpeedUnderrateBonus,
    compactDeltaSpeedBridgeBonus: t.compactDeltaSpeedBridgeBonus,
    simpleHighDeltaSpeedBridgeBonus: t.simpleHighDeltaSpeedBridgeBonus,
    sustainedLightJumpstreamBonus: t.sustainedLightJumpstreamBonus,
    baseRateSubGammaStreamBonus: t.baseRateSubGammaStreamBonus,
    compactModerateChordSpeedBonus: t.compactModerateChordSpeedBonus,
    speedEnduranceBonus: t.speedEnduranceBonus,
    highSpeedEndgameBonus: t.highSpeedEndgameBonus,
    lowChordSpeedjackAnchorBonus: t.lowChordSpeedjackAnchorBonus,
    variedLowChordSpeedjackBridgeBonus: t.variedLowChordSpeedjackBridgeBonus,
    variedLowChordSpeedCompression: t.variedLowChordSpeedCompression,
    midVarietyHighSpeedCompression: t.midVarietyHighSpeedCompression,
    lowMidRateOverpromotionCompression: t.lowMidRateOverpromotionCompression,
    lowMidSustainedPressureCompression: t.lowMidSustainedPressureCompression,
    jackPracticePatternInflationCompression: practice.compressions.jack,
    streamPracticePatternInflationCompression: practice.compressions.stream,
    jumpstreamPracticePatternInflationCompression: practice.compressions.jumpstream,
    handstreamPracticePatternInflationCompression: practice.compressions.handstream,
    staminaPracticePatternInflationCompression: practice.compressions.stamina,
    chordjackPracticePatternInflationCompression: practice.compressions.chordjack,
    techPracticePatternInflationCompression: practice.compressions.tech,
    extremeChordwallSpeedBonus: t.extremeChordwallSpeedBonus,
    fastSimpleChordWallJackFloorBonus: t.fastSimpleChordWallJackFloorBonus,
    sustainedHighChordWallBonus: t.sustainedHighChordWallBonus,
    staminaEnduranceBonus: t.staminaEnduranceBonus,
    longSteadyStreamBonus: t.longSteadyStreamBonus,
    burstTechBonus: t.burstTechBonus,
    lowSrTechnicalRhythmBonus: t.lowSrTechnicalRhythmBonus,
    lowerRateTechBridgeBonus: t.lowerRateTechBridgeBonus,
    baseRateTechCompression: t.baseRateTechCompression,
    ratePackTechStructuralCompression: t.ratePackTechStructuralCompression,
    syncopatedChordTechBonus: t.syncopatedChordTechBonus,
    compactChordSwitchTechBonus: t.compactChordSwitchTechBonus,
    technicalAnchorBonus: t.technicalAnchorBonus,
    highRatePackTechnicalAnchorCompression: t.highRatePackTechnicalAnchorCompression,
    highRateTechnicalAnchorFloorBonus: t.highRateTechnicalAnchorFloorBonus,
    compactTechnicalMarathonBonus: t.compactTechnicalMarathonBonus,
    earlyVariedPatternTechBonus: t.earlyVariedPatternTechBonus,
    lightRowBurstStreamBonus: t.lightRowBurstStreamBonus,
    compactChordFlowTechBonus: t.compactChordFlowTechBonus,
    fastTechnicalSpeedFloorBonus: t.fastTechnicalSpeedFloorBonus,
    variedTechnicalAnchorBridgeBonus: t.variedTechnicalAnchorBridgeBonus,
    moderateBurstTechCompression: t.moderateBurstTechCompression,
    lowDensityChordFlowTechCompression: t.lowDensityChordFlowTechCompression,
    introHighChordFlowTechCompression: t.introHighChordFlowTechCompression,
    earlyLowEntropyTechCompression: t.earlyLowEntropyTechCompression,
    sparseLowSrTechVocabularyCompression: t.sparseLowSrTechVocabularyCompression,
    compactHighChordTechCompression: t.compactHighChordTechCompression,
    shortSpikeCompression: t.shortSpikeCompression,
    localizedJumptrillSpikeCompression: t.localizedJumptrillSpikeCompression,
    chordedSpeedBonus: t.chordedSpeedBonus,
    denseChordedSpeedBonus: t.denseChordedSpeedBonus,
    chordjackEnduranceMultiplier: t.chordjackEnduranceMultiplier,
    highChordJackBonus: t.highChordJackBonus,
    highChordSoftJackPenalty: t.highChordSoftJackPenalty,
    denseJackSrCompression: t.denseJackSrCompression,
    denseJackTechNerf: t.denseJackTechNerf,
    lowSrDenseWallJackBonus: t.lowSrDenseWallJackBonus,
    compactJackUnderrateBonus: t.compactJackUnderrateBonus,
    lowRateHighChordJackBonus: t.lowRateHighChordJackBonus,
    slowRepetitiveJackstreamBonus: t.slowRepetitiveJackstreamBonus,
    ratedRepetitiveSpeedjackBonus: t.ratedRepetitiveSpeedjackBonus,
    repetitiveSpeedjackTechCompression: t.repetitiveSpeedjackTechCompression,
    compactJackOverboostCompression: t.compactJackOverboostCompression,
    compactHighChordDeltaJackBonus: t.compactHighChordDeltaJackBonus,
    mediumWallJackSrCompression: t.mediumWallJackSrCompression,
    denseWallJackPenaltyRelief: t.denseWallJackPenaltyRelief,
    wallJackTechNerf: t.wallJackTechNerf,
    lowChordBurstStreamNerf: t.lowChordBurstStreamNerf,
    lowChordBurstTechNerf: t.lowChordBurstTechNerf,
    farmJumptrillJackCompression: t.farmJumptrillJackCompression,
    farmJumptrillStreamCompression: t.farmJumptrillStreamCompression,
    farmJumptrillHandstreamCompression: t.farmJumptrillHandstreamCompression,
    farmJumptrillStaminaCompression: t.farmJumptrillStaminaCompression,
    farmJumptrillChordjackCompression: t.farmJumptrillChordjackCompression,
    farmJumptrillTechCompression: t.farmJumptrillTechCompression,
    shortDenseChordWallPenalty: t.shortDenseChordWallPenalty,
    highRateShortDenseChordWallPenalty: t.highRateShortDenseChordWallPenalty,
    longMidChordSrNerf: t.longMidChordSrNerf,
    moderateMidChordStaminaNerf: t.moderateMidChordStaminaNerf,
    midChordRateCompressionNerf: t.midChordRateCompressionNerf,
    highNoteMidRateHandstreamNerf: t.highNoteMidRateHandstreamNerf,
    highEndMidChordStaminaNerf: t.highEndMidChordStaminaNerf,
    longJumpstreamStaminaCompression: t.longJumpstreamStaminaCompression,
    simpleLongJumpstreamPatternCompression: t.simpleLongJumpstreamPatternCompression,
    deltaHighMidChordTransitionNerf: t.deltaHighMidChordTransitionNerf,
    longSparseStreamCompression: t.longSparseStreamCompression,
    longSparseJackDropJackCompression: t.longSparseJackDropJackCompression,
    longSparseJackDropStreamCompression: t.longSparseJackDropStreamCompression,
    longSparseJackDropHandstreamCompression: t.longSparseJackDropHandstreamCompression,
    longSparseJackDropStaminaCompression: t.longSparseJackDropStaminaCompression,
    longSparseJackDropChordjackCompression: t.longSparseJackDropChordjackCompression,
    longSparseJackDropTechCompression: t.longSparseJackDropTechCompression,
    denseChordStaminaCompression: t.denseChordStaminaCompression,
    shortLnHybridStructuralCompression: t.shortLnHybridStructuralCompression,
    lowChordSteadySpeedStructuralCompression: t.lowChordSteadySpeedStructuralCompression,
    moderateChordSteadyStreamStructuralCompression: t.moderateChordSteadyStreamStructuralCompression,
    compactHandstreamStaminaStructuralCompression: t.compactHandstreamStaminaStructuralCompression,
    compactHandstreamStaminaTechCompression: t.compactHandstreamStaminaTechCompression,
    compactTechnicalFlowStructuralCompression: t.compactTechnicalFlowStructuralCompression,
    compactChordWallStructuralCompression: t.compactChordWallStructuralCompression,
    simpleDenseChordWallStructuralCompression: t.simpleDenseChordWallStructuralCompression,
    lowRateDenseChordWallCompression: t.lowRateDenseChordWallCompression,
    simpleMidHighChordWallStructuralCompression: t.simpleMidHighChordWallStructuralCompression,
    awkwardMidRateChordjackWallCompression: t.awkwardMidRateChordjackWallCompression,
    midHighChordSustainedTechStructuralCompression: t.midHighChordSustainedTechStructuralCompression,
    marathonTechnicalEnduranceBonus: t.marathonTechnicalEnduranceBonus,
    shortDenseWallSrCompression: t.shortDenseWallSrCompression,
    lowSrShortDenseWallCompression: t.lowSrShortDenseWallCompression,
    mediumWallJackOverrateCompression: t.mediumWallJackOverrateCompression,
    longHighChordChordjackCompression: t.longHighChordChordjackCompression,
    midChordSpeedjackJackBonus: t.midChordSpeedjackJackBonus,
    midChordSpeedjackTechCompression: t.midChordSpeedjackTechCompression,
    highRateMidChordSpeedjackJackBonus: t.highRateMidChordSpeedjackJackBonus,
    longGammaHighChordjackFloorBonus: t.longGammaHighChordjackFloorBonus,
    heldLongGammaHighChordjackFloorBonus: t.heldLongGammaHighChordjackFloorBonus,
    midHighChordGammaCompression: t.midHighChordGammaCompression,
    compactPureChordjackStaminaCompression: t.compactPureChordjackStaminaCompression,
    shortSimpleChordjackWallStructuralCompression: t.shortSimpleChordjackWallStructuralCompression,
    shortHighChordWallStructuralCompression: t.shortHighChordWallStructuralCompression,
    lowEndLongMidChordStaminaFloorBonus: t.lowEndLongMidChordStaminaFloorBonus,
    jackBonus: t.jackBonus,
    streamBonus: t.streamBonus,
    jumpstreamBonus: t.jumpstreamBonus,
    staminaBonus: t.staminaBonus,
    handstreamBonus: t.handstreamBonus,
    chordjackBonus: t.chordjackBonus,
    techBonus: t.techBonus,
  };
}

export function scoringContributions(base: number, t: DebugTerms): Record<DanSkillFamily, DanScoreContribution[]> {
  return {
    jack: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "jackBonus", value: t.jackBonus, description: "Jack pressure and high-chord jack reward." },
      { id: "extremeChordwallSpeedBonus", value: t.extremeChordwallSpeedBonus, description: "Floor for extreme dense chordwall speed where peak and sustained wall pressure exceed ordinary jack calibration." },
      { id: "denseSimpleChordWallRateBonus", value: t.denseSimpleChordWallRateBonus, description: "Floor for dense simple chord walls once jack pressure crosses the next rate step." },
      { id: "highEndFastWallJackBonus", value: t.highEndFastWallJackBonus, description: "Top-end floor for long fast wall-jack files with sustained same-column pressure." },
      { id: "midHighChordjackDeltaBridgeBonus", value: t.midHighChordjackDeltaBridgeBonus, description: "Bridge for mid-high chordjack files where fast-row and same-column pressure reach low-delta shape." },
      { id: "highRateVariedWallJackBridgeBonus", value: t.highRateVariedWallJackBridgeBonus, description: "Bridge for higher-rate varied wall-jacks once entropy and jack pressure exceed the plain-wall band." },
      { id: "marathonTechnicalEnduranceBonus", value: t.marathonTechnicalEnduranceBonus, description: "Reward for very long high-pressure technical endurance where extracted pressure is otherwise too conservative." },
      { id: "midChordSpeedjackJackBonus", value: t.midChordSpeedjackJackBonus, description: "Reward for mid-chord speedjack pressure that should route as jack instead of tech." },
      { id: "highRateMidChordSpeedjackJackBonus", value: t.highRateMidChordSpeedjackJackBonus, description: "Floor for high-rate mid-chord speedjack pressure above the ordinary mid-chord gate." },
      { id: "lowSrDenseWallJackBonus", value: t.lowSrDenseWallJackBonus, description: "Dense wall-jack reward where SR underrates slow high-chord repetition." },
      { id: "compactJackUnderrateBonus", value: t.compactJackUnderrateBonus, description: "Compact dense jack files around gamma that SR tends to underrate." },
      { id: "lowRateHighChordJackBonus", value: t.lowRateHighChordJackBonus, description: "High-chord lower-rate jack reward for gamma-range files." },
      { id: "slowRepetitiveJackstreamBonus", value: t.slowRepetitiveJackstreamBonus, description: "Reward for slow repetitive jackstream where row timing is simple but same-column pressure is high." },
      { id: "ratedRepetitiveSpeedjackBonus", value: t.ratedRepetitiveSpeedjackBonus, description: "Reward for rate-scaled repetitive speedjack pressure that should stay in the jack family." },
      { id: "compactHighChordDeltaJackBonus", value: t.compactHighChordDeltaJackBonus, description: "Compact high-chord wall-jack reward around low delta." },
      { id: "denseWallJackPenaltyRelief", value: t.denseWallJackPenaltyRelief, description: "Restores high-chord wall penalty when same-column jack pressure is present at lower SR." },
      { id: "midRatePlainWallJackCompression", value: -t.midRatePlainWallJackCompression, description: "Compression for plain mid-rate wall-jacks before timing variety catches up." },
      { id: "plainHighChordWallRateCompression", value: -t.plainHighChordWallRateCompression, description: "Compression for plain high-chord walls where rate lifts peak pressure before timing variety appears." },
      { id: "variedMidHighChordWallCompression", value: -t.variedMidHighChordWallCompression, description: "Compression for varied mid-high chord walls that inflate SR before fast-row pressure arrives." },
      { id: "lowRateMidChordJackCompression", value: -t.lowRateMidChordJackCompression, description: "Compression for low-rate mid-chord jack files where jack pressure overstates dan level." },
      { id: "introMidChordJackCompression", value: -t.introMidChordJackCompression, description: "Compression for introductory mid-chord jack files with low row speed." },
      { id: "highChordSoftJackPenalty", value: -t.highChordSoftJackPenalty, description: "Penalty for chord walls without enough jack pressure." },
      { id: "denseJackSrCompression", value: -t.denseJackSrCompression, description: "Compression for short dense jack files at high SR." },
      { id: "mediumWallJackSrCompression", value: -t.mediumWallJackSrCompression, description: "Compression for medium wall-jacks where SR overstates dan pressure." },
      { id: "compactJackOverboostCompression", value: -t.compactJackOverboostCompression, description: "Trims compact jack boost when higher-rate pressure is already represented." },
      { id: "farmJumptrillJackCompression", value: -t.farmJumptrillJackCompression, description: "Compression for long farm jumptrills that only become vibro-like under rate." },
      { id: "longSparseJackDropJackCompression", value: -t.longSparseJackDropJackCompression, description: "Compression for long files whose difficulty is concentrated in jack drops rather than full-chart dan pressure." },
      { id: "shortLnHybridStructuralCompression", value: -t.shortLnHybridStructuralCompression, description: "Compression for mixed short-LN charts where LN density overstates rice dan pressure." },
      { id: "lowChordSteadySpeedStructuralCompression", value: -t.lowChordSteadySpeedStructuralCompression, description: "Compression for low-chord steady speed where density overstates whole-chart dan pressure." },
      { id: "moderateChordSteadyStreamStructuralCompression", value: -t.moderateChordSteadyStreamStructuralCompression, description: "Compression for long low-mid chord steady stream where sustained density overstates dan pressure." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression, description: "Compression for compact handstream stamina where chord changes overstate dan pressure." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression * 0.65, description: "Shared compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "lowRateDenseChordWallCompression", value: -t.lowRateDenseChordWallCompression, description: "Compression for low-rate dense chord walls whose chord density overstates dan pressure before sustained speed arrives." },
      { id: "simpleMidHighChordWallStructuralCompression", value: -t.simpleMidHighChordWallStructuralCompression, description: "Compression for simple mid-high chord walls whose chord density overstates jack dan pressure." },
      { id: "awkwardMidRateChordjackWallCompression", value: -t.awkwardMidRateChordjackWallCompression, description: "Compression for mid-rate chordjack walls whose awkwardness is real but overpromoted below full-rate pressure." },
      { id: "midHighChordSustainedTechStructuralCompression", value: -t.midHighChordSustainedTechStructuralCompression, description: "Compression for sustained mid-high chord tech walls where row flow is simpler than the pressure estimate." },
      { id: "shortDenseWallSrCompression", value: -t.shortDenseWallSrCompression, description: "Compression for short dense wall-jack files where SR overstates dan pressure." },
      { id: "lowSrShortDenseWallCompression", value: -t.lowSrShortDenseWallCompression, description: "Compression for lower-SR short wall-jack files where dense chords overstate dan pressure." },
      { id: "mediumWallJackOverrateCompression", value: -t.mediumWallJackOverrateCompression, description: "Compression for medium wall-jacks where jack pressure is already represented by SR." },
      { id: "compactPureChordjackStaminaCompression", value: -t.compactPureChordjackStaminaCompression, description: "Compression for compact pure chordjack stamina where lower rates overstate dan pressure." },
      { id: "shortSimpleChordjackWallStructuralCompression", value: -t.shortSimpleChordjackWallStructuralCompression, description: "Compression for short simple chordjack walls where chord density overstates dan pressure." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for files whose difficulty is mostly a short isolated spike." },
      { id: "localizedJumptrillSpikeCompression", value: -t.localizedJumptrillSpikeCompression, description: "Compression for maps whose hardest 5s jumptrill or vibro section is much denser than the surrounding file." },
    ],
    stream: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "streamBonus", value: t.streamBonus, description: "Speed and sustained stream pressure." },
      { id: "highSpeedEndgameBonus", value: t.highSpeedEndgameBonus, description: "Floor for continuous low-chord speed/endurance charts at high sustained NPS." },
      { id: "lowChordSpeedjackAnchorBonus", value: t.lowChordSpeedjackAnchorBonus, description: "Floor for low-chord speedjack anchor patterns where same-column pressure suppresses ordinary stream scoring." },
      { id: "highEntropyLowChordEnduranceBridgeBonus", value: t.highEntropyLowChordEnduranceBridgeBonus, description: "Bridge for low-chord endurance streams whose row-speed coverage and timing entropy exceed the ordinary speed floor." },
      { id: "marathonTechnicalEnduranceBonus", value: t.marathonTechnicalEnduranceBonus * 0.85, description: "Shared reward for very long high-pressure technical endurance." },
      { id: "lightChordGammaSpeedFloorBonus", value: t.lightChordGammaSpeedFloorBonus, description: "Gamma floor for lower-rate light-chord steady speed." },
      { id: "compactDeltaSpeedBridgeBonus", value: t.compactDeltaSpeedBridgeBonus, description: "Small bridge for compact low-chord speed files sitting just below the middle-delta boundary." },
      { id: "simpleHighDeltaSpeedBridgeBonus", value: t.simpleHighDeltaSpeedBridgeBonus, description: "Bridge for simple low-chord sustained speed just above the compact delta-speed window." },
      { id: "sustainedLightJumpstreamBonus", value: t.sustainedLightJumpstreamBonus, description: "Rate-scaled reward for continuous light jumpstream with high sustain and low jack pressure." },
      { id: "baseRateSubGammaStreamBonus", value: t.baseRateSubGammaStreamBonus, description: "Beta floor for base-rate low-chord stream sitting just below gamma speed thresholds." },
      { id: "compactModerateChordSpeedBonus", value: t.compactModerateChordSpeedBonus, description: "Compact moderate-chord speed reward around beta." },
      { id: "lightRowBurstStreamBonus", value: t.lightRowBurstStreamBonus, description: "Reward for light stream charts with frequent row bursts and varied timing." },
      { id: "longSparseStreamCompression", value: -t.longSparseStreamCompression, description: "Compression for long sparse dumpstreams with steady density but low chord and tech variety." },
      { id: "sparseLowSrTechVocabularyCompression", value: -t.sparseLowSrTechVocabularyCompression, description: "Compression for very sparse low-SR charts where timing vocabulary exceeds actual pressure." },
      { id: "lowChordBurstStreamNerf", value: -t.lowChordBurstStreamNerf, description: "Compression for low-chord burst streams with jack pressure." },
      { id: "variedLowChordSpeedCompression", value: -t.variedLowChordSpeedCompression, description: "Compression for varied low-chord speed charts where timing variety makes the endgame floor too aggressive." },
      { id: "thinLowChordSpeedCompression", value: -t.thinLowChordSpeedCompression, description: "Compression for thin low-chord speed files whose timing variety is present but not backed by chord density." },
      { id: "highVarietyThinStreamEdgeCompression", value: -t.highVarietyThinStreamEdgeCompression, description: "Compression for high-variety thin streams near the gamma/delta edge." },
      { id: "farmJumptrillStreamCompression", value: -t.farmJumptrillStreamCompression, description: "Compression for long farm jumptrills with non-stream difficulty profile." },
      { id: "longSparseJackDropStreamCompression", value: -t.longSparseJackDropStreamCompression, description: "Compression for long sparse jack-drop files." },
      { id: "shortLnHybridStructuralCompression", value: -t.shortLnHybridStructuralCompression, description: "Shared compression for mixed short-LN charts where LN density overstates rice dan pressure." },
      { id: "lowChordSteadySpeedStructuralCompression", value: -t.lowChordSteadySpeedStructuralCompression, description: "Compression for low-chord steady speed where density overstates whole-chart dan pressure." },
      { id: "moderateChordSteadyStreamStructuralCompression", value: -t.moderateChordSteadyStreamStructuralCompression, description: "Compression for long low-mid chord steady stream where sustained density overstates dan pressure." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression, description: "Compression for compact handstream stamina where chord changes overstate dan pressure." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression * 0.6, description: "Shared compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "lowRateDenseChordWallCompression", value: -t.lowRateDenseChordWallCompression, description: "Compression for low-rate dense chord walls whose chord density overstates dan pressure before sustained speed arrives." },
      { id: "simpleMidHighChordWallStructuralCompression", value: -t.simpleMidHighChordWallStructuralCompression, description: "Compression for simple mid-high chord walls whose chord density overstates jack dan pressure." },
      { id: "awkwardMidRateChordjackWallCompression", value: -t.awkwardMidRateChordjackWallCompression, description: "Compression for mid-rate chordjack walls whose awkwardness is real but overpromoted below full-rate pressure." },
      { id: "midHighChordSustainedTechStructuralCompression", value: -t.midHighChordSustainedTechStructuralCompression * 0.85, description: "Compression for sustained mid-high chord tech walls where row flow is simpler than the pressure estimate." },
      { id: "shortDenseWallSrCompression", value: -t.shortDenseWallSrCompression, description: "Shared compression for short dense wall-jack files." },
      { id: "lowSrShortDenseWallCompression", value: -t.lowSrShortDenseWallCompression, description: "Shared compression for lower-SR short wall-jack files." },
      { id: "mediumWallJackOverrateCompression", value: -t.mediumWallJackOverrateCompression, description: "Shared compression for medium wall-jack files." },
      { id: "compactPureChordjackStaminaCompression", value: -t.compactPureChordjackStaminaCompression, description: "Shared compression for compact pure chordjack stamina files." },
      { id: "shortSimpleChordjackWallStructuralCompression", value: -t.shortSimpleChordjackWallStructuralCompression, description: "Compression for short simple chordjack walls where chord density overstates dan pressure." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for files whose pressure is concentrated in one short spike." },
      { id: "localizedJumptrillSpikeCompression", value: -t.localizedJumptrillSpikeCompression, description: "Compression for maps whose hardest 5s jumptrill or vibro section is much denser than the surrounding file." },
    ],
    jumpstream: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "jumpstreamBonus", value: t.jumpstreamBonus, description: "Sustained two-note chord stream pressure." },
      { id: "sustainedLightJumpstreamBonus", value: t.sustainedLightJumpstreamBonus, description: "Rate-scaled reward for continuous light jumpstream with high sustain and low jack pressure." },
      { id: "compactModerateChordSpeedBonus", value: t.compactModerateChordSpeedBonus * 0.75, description: "Compact moderate-chord speed reward around beta." },
      { id: "speedEnduranceBonus", value: t.speedEnduranceBonus * 0.35, description: "Shared endurance reward for fast sustained chorded streams." },
      { id: "longSteadyStreamBonus", value: t.longSteadyStreamBonus * 0.35, description: "Shared reward for long steady chorded stream coverage." },
      { id: "lowRateMidChordJackCompression", value: -t.lowRateMidChordJackCompression * 0.5, description: "Compression for low-rate mid-chord jack files where jack pressure overstates dan level." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression * 0.65, description: "Compression when the chart reads more like compact handstream stamina than jumpstream." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression * 0.7, description: "Shared compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for files whose pressure is concentrated in one short spike." },
    ],
    handstream: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "handstreamBonus", value: t.handstreamBonus, description: "Mid-chord sustained stream pressure." },
      { id: "fastMidChordHandstreamBridgeBonus", value: t.fastMidChordHandstreamBridgeBonus, description: "Bridge for fast mid-chord handstream with sustained row coverage." },
      { id: "marathonTechnicalEnduranceBonus", value: t.marathonTechnicalEnduranceBonus * 0.7, description: "Shared reward for very long high-pressure technical endurance." },
      { id: "moderateMidChordStaminaNerf", value: -t.moderateMidChordStaminaNerf * 0.25, description: "Shared mid-chord stamina compression." },
      { id: "highEndMidChordStaminaNerf", value: -t.highEndMidChordStaminaNerf * 0.35, description: "Shared high-end mid-chord stamina compression." },
      { id: "longJumpstreamStaminaCompression", value: -t.longJumpstreamStaminaCompression * 0.45, description: "Compression for long steady jumpstream stamina marathons with low jack pressure." },
      { id: "simpleLongJumpstreamPatternCompression", value: -t.simpleLongJumpstreamPatternCompression * 0.35, description: "Compression for long steady jumpstream marathons with simple timing vocabulary." },
      { id: "farmJumptrillHandstreamCompression", value: -t.farmJumptrillHandstreamCompression, description: "Compression for jumptrill farm patterns mistaken for handstream." },
      { id: "longSparseJackDropHandstreamCompression", value: -t.longSparseJackDropHandstreamCompression, description: "Compression for long sparse jack-drop files." },
      { id: "shortLnHybridStructuralCompression", value: -t.shortLnHybridStructuralCompression, description: "Shared compression for mixed short-LN charts where LN density overstates rice dan pressure." },
      { id: "lowChordSteadySpeedStructuralCompression", value: -t.lowChordSteadySpeedStructuralCompression * 0.85, description: "Compression for low-chord steady speed where density overstates whole-chart dan pressure." },
      { id: "moderateChordSteadyStreamStructuralCompression", value: -t.moderateChordSteadyStreamStructuralCompression, description: "Compression for long low-mid chord steady stream where sustained density overstates dan pressure." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression, description: "Compression for compact handstream stamina where chord changes overstate dan pressure." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression * 0.7, description: "Shared compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "lowRateDenseChordWallCompression", value: -t.lowRateDenseChordWallCompression, description: "Compression for low-rate dense chord walls whose chord density overstates dan pressure before sustained speed arrives." },
      { id: "simpleMidHighChordWallStructuralCompression", value: -t.simpleMidHighChordWallStructuralCompression, description: "Compression for simple mid-high chord walls whose chord density overstates jack dan pressure." },
      { id: "awkwardMidRateChordjackWallCompression", value: -t.awkwardMidRateChordjackWallCompression, description: "Compression for mid-rate chordjack walls whose awkwardness is real but overpromoted below full-rate pressure." },
      { id: "midHighChordSustainedTechStructuralCompression", value: -t.midHighChordSustainedTechStructuralCompression, description: "Compression for sustained mid-high chord tech walls where row flow is simpler than the pressure estimate." },
      { id: "shortDenseWallSrCompression", value: -t.shortDenseWallSrCompression, description: "Shared compression for short dense wall-jack files." },
      { id: "lowSrShortDenseWallCompression", value: -t.lowSrShortDenseWallCompression, description: "Shared compression for lower-SR short wall-jack files." },
      { id: "mediumWallJackOverrateCompression", value: -t.mediumWallJackOverrateCompression, description: "Shared compression for medium wall-jack files." },
      { id: "compactPureChordjackStaminaCompression", value: -t.compactPureChordjackStaminaCompression, description: "Shared compression for compact pure chordjack stamina files." },
      { id: "shortSimpleChordjackWallStructuralCompression", value: -t.shortSimpleChordjackWallStructuralCompression, description: "Compression for short simple chordjack walls where chord density overstates dan pressure." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for short spike-dominant files." },
      { id: "localizedJumptrillSpikeCompression", value: -t.localizedJumptrillSpikeCompression, description: "Compression for maps whose hardest 5s jumptrill or vibro section is much denser than the surrounding file." },
    ],
    stamina: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "staminaBonus", value: t.staminaBonus, description: "Sustained NPS and endurance reward." },
      { id: "highSpeedEndgameBonus", value: t.highSpeedEndgameBonus * 0.65, description: "Shared high-speed floor for continuous low-chord endurance pressure." },
      { id: "marathonTechnicalEnduranceBonus", value: t.marathonTechnicalEnduranceBonus * 0.9, description: "Shared reward for very long high-pressure technical endurance." },
      { id: "moderateMidChordStaminaNerf", value: -t.moderateMidChordStaminaNerf, description: "Compression for slower long mid-chord stamina." },
      { id: "midChordRateCompressionNerf", value: -t.midChordRateCompressionNerf, description: "Compression for early mid-chord rate scaling." },
      { id: "highNoteMidRateHandstreamNerf", value: -t.highNoteMidRateHandstreamNerf, description: "Compression for long handstream rates before delta range." },
      { id: "highEndMidChordStaminaNerf", value: -t.highEndMidChordStaminaNerf, description: "Compression for high-end mid-chord stamina." },
      { id: "longJumpstreamStaminaCompression", value: -t.longJumpstreamStaminaCompression, description: "Compression for long steady jumpstream stamina where endurance matters but pattern density is not beta-level." },
      { id: "simpleLongJumpstreamPatternCompression", value: -t.simpleLongJumpstreamPatternCompression, description: "Compression for long steady jumpstream stamina with simple pattern vocabulary." },
      { id: "deltaHighMidChordTransitionNerf", value: -t.deltaHighMidChordTransitionNerf, description: "Transition compression around delta high handstream." },
      { id: "farmJumptrillStaminaCompression", value: -t.farmJumptrillStaminaCompression, description: "Compression for long jumptrill farm patterns with easy base stamina." },
      { id: "longSparseJackDropStaminaCompression", value: -t.longSparseJackDropStaminaCompression, description: "Compression for long sparse jack-drop files." },
      { id: "denseChordStaminaCompression", value: -t.denseChordStaminaCompression, description: "Compression for dense mid-chord stamina where base-rate SR overstates dan pressure." },
      { id: "lowEndLongMidChordStaminaFloorBonus", value: t.lowEndLongMidChordStaminaFloorBonus, description: "Small floor for long low-end mid-chord stamina files sitting on a dan boundary." },
      { id: "shortLnHybridStructuralCompression", value: -t.shortLnHybridStructuralCompression, description: "Shared compression for mixed short-LN charts where LN density overstates rice dan pressure." },
      { id: "lowChordSteadySpeedStructuralCompression", value: -t.lowChordSteadySpeedStructuralCompression * 0.9, description: "Compression for low-chord steady speed where density overstates whole-chart dan pressure." },
      { id: "moderateChordSteadyStreamStructuralCompression", value: -t.moderateChordSteadyStreamStructuralCompression, description: "Compression for long low-mid chord steady stream where sustained density overstates dan pressure." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression, description: "Compression for compact handstream stamina where chord changes overstate dan pressure." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression * 0.6, description: "Shared compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "lowRateDenseChordWallCompression", value: -t.lowRateDenseChordWallCompression, description: "Compression for low-rate dense chord walls whose chord density overstates dan pressure before sustained speed arrives." },
      { id: "simpleMidHighChordWallStructuralCompression", value: -t.simpleMidHighChordWallStructuralCompression, description: "Compression for simple mid-high chord walls whose chord density overstates jack dan pressure." },
      { id: "awkwardMidRateChordjackWallCompression", value: -t.awkwardMidRateChordjackWallCompression, description: "Compression for mid-rate chordjack walls whose awkwardness is real but overpromoted below full-rate pressure." },
      { id: "midHighChordSustainedTechStructuralCompression", value: -t.midHighChordSustainedTechStructuralCompression, description: "Compression for sustained mid-high chord tech walls where row flow is simpler than the pressure estimate." },
      { id: "shortDenseWallSrCompression", value: -t.shortDenseWallSrCompression, description: "Shared compression for short dense wall-jack files." },
      { id: "lowSrShortDenseWallCompression", value: -t.lowSrShortDenseWallCompression, description: "Shared compression for lower-SR short wall-jack files." },
      { id: "mediumWallJackOverrateCompression", value: -t.mediumWallJackOverrateCompression, description: "Shared compression for medium wall-jack files." },
      { id: "compactPureChordjackStaminaCompression", value: -t.compactPureChordjackStaminaCompression, description: "Shared compression for compact pure chordjack stamina files." },
      { id: "shortSimpleChordjackWallStructuralCompression", value: -t.shortSimpleChordjackWallStructuralCompression, description: "Compression for short simple chordjack walls where chord density overstates dan pressure." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for files with low sustained pressure relative to peak burst pressure." },
      { id: "localizedJumptrillSpikeCompression", value: -t.localizedJumptrillSpikeCompression, description: "Compression for maps whose hardest 5s jumptrill or vibro section is much denser than the surrounding file." },
    ],
    chordjack: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "chordjackBonus", value: t.chordjackBonus, description: "Chordjack pressure after wall/endurance penalties." },
      { id: "extremeChordwallSpeedBonus", value: t.extremeChordwallSpeedBonus * 0.6, description: "Shared floor for extreme dense chordwall speed in chordjack routing." },
      { id: "lowRateChordjackWallFloorBonus", value: t.lowRateChordjackWallFloorBonus, description: "Floor for low-rate high-chord walls where chordjack pressure is understated." },
      { id: "marathonTechnicalEnduranceBonus", value: t.marathonTechnicalEnduranceBonus * 0.75, description: "Shared reward for very long high-pressure technical endurance." },
      { id: "slowRepetitiveJackstreamBonus", value: t.slowRepetitiveJackstreamBonus * 0.55, description: "Partial chordjack credit for slow repetitive jackstream pressure." },
      { id: "ratedRepetitiveSpeedjackBonus", value: t.ratedRepetitiveSpeedjackBonus * 0.55, description: "Partial chordjack credit for rate-scaled repetitive speedjack pressure." },
      { id: "midChordSpeedjackJackBonus", value: t.midChordSpeedjackJackBonus, description: "Reward for mid-chord speedjack pressure in chordjack-like files." },
      { id: "farmJumptrillChordjackCompression", value: -t.farmJumptrillChordjackCompression, description: "Compression for jumptrills that inflate chordjack pressure." },
      { id: "longSparseJackDropChordjackCompression", value: -t.longSparseJackDropChordjackCompression, description: "Compression for long sparse jack-drop files." },
      { id: "shortLnHybridStructuralCompression", value: -t.shortLnHybridStructuralCompression, description: "Shared compression for mixed short-LN charts where LN density overstates rice dan pressure." },
      { id: "lowChordSteadySpeedStructuralCompression", value: -t.lowChordSteadySpeedStructuralCompression * 0.8, description: "Compression for low-chord steady speed where density overstates whole-chart dan pressure." },
      { id: "moderateChordSteadyStreamStructuralCompression", value: -t.moderateChordSteadyStreamStructuralCompression, description: "Compression for long low-mid chord steady stream where sustained density overstates dan pressure." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression, description: "Compression for compact handstream stamina where chord changes overstate dan pressure." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression * 0.75, description: "Shared compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "lowRateDenseChordWallCompression", value: -t.lowRateDenseChordWallCompression, description: "Compression for low-rate dense chord walls whose chord density overstates dan pressure before sustained speed arrives." },
      { id: "simpleMidHighChordWallStructuralCompression", value: -t.simpleMidHighChordWallStructuralCompression, description: "Compression for simple mid-high chord walls whose chord density overstates jack dan pressure." },
      { id: "awkwardMidRateChordjackWallCompression", value: -t.awkwardMidRateChordjackWallCompression, description: "Compression for mid-rate chordjack walls whose awkwardness is real but overpromoted below full-rate pressure." },
      { id: "midHighChordSustainedTechStructuralCompression", value: -t.midHighChordSustainedTechStructuralCompression, description: "Compression for sustained mid-high chord tech walls where row flow is simpler than the pressure estimate." },
      { id: "shortDenseWallSrCompression", value: -t.shortDenseWallSrCompression, description: "Shared compression for short dense wall-jack files." },
      { id: "lowSrShortDenseWallCompression", value: -t.lowSrShortDenseWallCompression, description: "Shared compression for lower-SR short wall-jack files." },
      { id: "mediumWallJackOverrateCompression", value: -t.mediumWallJackOverrateCompression, description: "Shared compression for medium wall-jack files." },
      { id: "longHighChordChordjackCompression", value: -t.longHighChordChordjackCompression, description: "Compression for long high-chord chordjack where SR overstates the dan jump." },
      { id: "compactPureChordjackStaminaCompression", value: -t.compactPureChordjackStaminaCompression, description: "Shared compression for compact pure chordjack stamina files." },
      { id: "shortSimpleChordjackWallStructuralCompression", value: -t.shortSimpleChordjackWallStructuralCompression, description: "Compression for short simple chordjack walls where chord density overstates dan pressure." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for short spike-dominant files." },
      { id: "localizedJumptrillSpikeCompression", value: -t.localizedJumptrillSpikeCompression, description: "Compression for maps whose hardest 5s jumptrill or vibro section is much denser than the surrounding file." },
    ],
    tech: [
      { id: "base", value: base, description: "Base pressure estimate from extracted density and stamina." },
      { id: "techBonus", value: t.techBonus, description: "Direction, chord-size, burst, and density tech pressure." },
      { id: "highSpeedEndgameBonus", value: t.highSpeedEndgameBonus * 0.85, description: "Shared high-speed floor for technical charts whose primary pressure is still continuous speed." },
      { id: "lowChordSpeedjackAnchorBonus", value: t.lowChordSpeedjackAnchorBonus * 0.6, description: "Partial speedjack anchor credit when low-chord repetition presents as technical speed." },
      { id: "marathonTechnicalEnduranceBonus", value: t.marathonTechnicalEnduranceBonus * 0.8, description: "Shared reward for very long high-pressure technical endurance." },
      { id: "denseJackTechNerf", value: -t.denseJackTechNerf, description: "Tech inflation removed for short dense jack files." },
      { id: "wallJackTechNerf", value: -t.wallJackTechNerf, description: "Tech inflation removed for dense jack-wall repetition." },
      { id: "lowChordBurstTechNerf", value: -t.lowChordBurstTechNerf, description: "Tech inflation removed for low-chord burst streams." },
      { id: "variedLowChordSpeedCompression", value: -t.variedLowChordSpeedCompression, description: "Compression for varied low-chord speed charts where timing variety makes the endgame floor too aggressive." },
      { id: "farmJumptrillTechCompression", value: -t.farmJumptrillTechCompression, description: "Tech inflation removed for long jumptrill farm patterns." },
      { id: "lowSrTechnicalRhythmBonus", value: t.lowSrTechnicalRhythmBonus, description: "Reward for low-SR tech cuts with fast row bursts, rhythm variation, and chord-size changes." },
      { id: "lowerRateTechBridgeBonus", value: t.lowerRateTechBridgeBonus, description: "Bridge for low-rate tech packs whose rhythm shape is present before full burst speed arrives." },
      { id: "syncopatedChordTechBonus", value: t.syncopatedChordTechBonus, description: "Reward for syncopated moderate-chord tech cuts with slower note NPS but awkward row flow." },
      { id: "compactChordSwitchTechBonus", value: t.compactChordSwitchTechBonus, description: "Reward for compact chord-switch tech with high fast-row ratio and anchor pressure." },
      { id: "technicalAnchorBonus", value: t.technicalAnchorBonus, description: "Reward for moderate-chord technical anchors with strong same-column pressure." },
      { id: "highRatePackTechnicalAnchorCompression", value: -t.highRatePackTechnicalAnchorCompression, description: "Removes technical-anchor inflation on high-rate charts with the rate-pack tech shape." },
      { id: "highRateTechnicalAnchorFloorBonus", value: t.highRateTechnicalAnchorFloorBonus, description: "Floor for high-rate technical anchors whose same-column pressure exceeds lower-rate pack calibration." },
      { id: "compactTechnicalMarathonBonus", value: t.compactTechnicalMarathonBonus, description: "Reward for compact technical marathons with sustained direction and chord-size pressure." },
      { id: "earlyVariedPatternTechBonus", value: t.earlyVariedPatternTechBonus, description: "Reward for early-dan charts with varied timing and same-column pressure." },
      { id: "compactChordFlowTechBonus", value: t.compactChordFlowTechBonus, description: "Reward for compact chord-flow tech with sustained direction changes." },
      { id: "fastTechnicalSpeedFloorBonus", value: t.fastTechnicalSpeedFloorBonus, description: "Floor for fast low-chord technical speed charts." },
      { id: "variedTechnicalAnchorBridgeBonus", value: t.variedTechnicalAnchorBridgeBonus, description: "Bridge for varied moderate-chord technical anchors sitting just below delta pressure." },
      { id: "lowChordTechnicalSpeedBridgeBonus", value: t.lowChordTechnicalSpeedBridgeBonus, description: "Bridge for low-chord technical speed charts with compact timing entropy." },
      { id: "moderateBurstTechCompression", value: -t.moderateBurstTechCompression, description: "Compression for mid-chord burst tech that was overpromoted by peak density alone." },
      { id: "lowDensityChordFlowTechCompression", value: -t.lowDensityChordFlowTechCompression, description: "Compression for low-density chord-flow charts where chord changes overstate dan pressure." },
      { id: "introHighChordFlowTechCompression", value: -t.introHighChordFlowTechCompression, description: "Compression for introductory high-chord flow with low row speed." },
      { id: "earlyLowEntropyTechCompression", value: -t.earlyLowEntropyTechCompression, description: "Compression for early low-density tech with simple row timing." },
      { id: "sparseLowSrTechVocabularyCompression", value: -t.sparseLowSrTechVocabularyCompression, description: "Compression for very sparse low-SR charts where timing vocabulary exceeds actual pressure." },
      { id: "lowRateTechnicalVocabularyCompression", value: -t.lowRateTechnicalVocabularyCompression, description: "Compression for low-rate technical rhythm where vocabulary exceeds the pressure ceiling." },
      { id: "compactHighChordTechCompression", value: -t.compactHighChordTechCompression, description: "Compression for compact high-chord technical marathons at the beta/gamma boundary." },
      { id: "baseRateTechCompression", value: -t.baseRateTechCompression, description: "Compression for the rate-pack tech shape where base-rate SR overstates the dan jump." },
      { id: "ratePackTechStructuralCompression", value: -t.ratePackTechStructuralCompression, description: "Compression for the rate-pack tech shape where fast-row coverage overstates whole-file tech pressure." },
      { id: "repetitiveSpeedjackTechCompression", value: -t.repetitiveSpeedjackTechCompression, description: "Tech inflation removed when the chart is repetitive jackstream or speedjack rather than pattern tech." },
      { id: "longSparseJackDropTechCompression", value: -t.longSparseJackDropTechCompression, description: "Tech inflation removed for long sparse jack-drop files." },
      { id: "shortLnHybridStructuralCompression", value: -t.shortLnHybridStructuralCompression, description: "Shared compression for mixed short-LN charts where LN density overstates rice dan pressure." },
      { id: "lowChordSteadySpeedStructuralCompression", value: -t.lowChordSteadySpeedStructuralCompression * 0.85, description: "Compression for low-chord steady speed where density overstates whole-chart dan pressure." },
      { id: "moderateChordSteadyStreamStructuralCompression", value: -t.moderateChordSteadyStreamStructuralCompression, description: "Compression for long low-mid chord steady stream where sustained density overstates dan pressure." },
      { id: "compactHandstreamStaminaStructuralCompression", value: -t.compactHandstreamStaminaStructuralCompression, description: "Compression for compact handstream stamina where chord changes overstate dan pressure." },
      { id: "compactHandstreamStaminaTechCompression", value: -t.compactHandstreamStaminaTechCompression, description: "Tech inflation removed for compact handstream stamina patterns." },
      { id: "compactTechnicalFlowStructuralCompression", value: -t.compactTechnicalFlowStructuralCompression, description: "Compression for compact technical flow whose local chord changes overstate dan pressure." },
      { id: "compactChordWallStructuralCompression", value: -t.compactChordWallStructuralCompression, description: "Compression for compact high-chord wall-jacks with limited whole-chart pressure." },
      { id: "simpleDenseChordWallStructuralCompression", value: -t.simpleDenseChordWallStructuralCompression, description: "Compression for simple dense chord walls with very low row-flow variety." },
      { id: "lowRateDenseChordWallCompression", value: -t.lowRateDenseChordWallCompression, description: "Compression for low-rate dense chord walls whose chord density overstates dan pressure before sustained speed arrives." },
      { id: "simpleMidHighChordWallStructuralCompression", value: -t.simpleMidHighChordWallStructuralCompression, description: "Compression for simple mid-high chord walls whose chord density overstates jack dan pressure." },
      { id: "awkwardMidRateChordjackWallCompression", value: -t.awkwardMidRateChordjackWallCompression, description: "Compression for mid-rate chordjack walls whose awkwardness is real but overpromoted below full-rate pressure." },
      { id: "midHighChordSustainedTechStructuralCompression", value: -t.midHighChordSustainedTechStructuralCompression, description: "Compression for sustained mid-high chord tech walls where row flow is simpler than the pressure estimate." },
      { id: "shortDenseWallSrCompression", value: -t.shortDenseWallSrCompression, description: "Shared compression for short dense wall-jack files." },
      { id: "lowSrShortDenseWallCompression", value: -t.lowSrShortDenseWallCompression, description: "Shared compression for lower-SR short wall-jack files." },
      { id: "mediumWallJackOverrateCompression", value: -t.mediumWallJackOverrateCompression, description: "Shared compression for medium wall-jack files." },
      { id: "midChordSpeedjackTechCompression", value: -t.midChordSpeedjackTechCompression, description: "Tech inflation removed from mid-chord speedjack files." },
      { id: "compactPureChordjackStaminaCompression", value: -t.compactPureChordjackStaminaCompression, description: "Shared compression for compact pure chordjack stamina files." },
      { id: "shortSimpleChordjackWallStructuralCompression", value: -t.shortSimpleChordjackWallStructuralCompression, description: "Compression for short simple chordjack walls where chord density overstates dan pressure." },
      { id: "shortSpikeCompression", value: -t.shortSpikeCompression, description: "Compression for tech estimates driven by a short isolated burst." },
      { id: "localizedJumptrillSpikeCompression", value: -t.localizedJumptrillSpikeCompression * 1.45, description: "Tech inflation removed when a localized jumptrill or vibro spike is not representative of whole-file tech pressure." },
    ],
    ln: [],
    dan: [],
  };
}
